import {
  Branch,
  User,
  Owner,
  Patient,
  VitalSigns,
  Consultation,
  Hospitalization,
  SurgeryRecord,
  LaboratoryOrder,
  ImagingStudy,
  VaccinationRecord,
  Product,
  Appointment,
  TriageEntry,
  Invoice,
  Estimate,
  CashRegisterSession,
  ClinicalDocument,
  AuditLog,
  PatientProblem,
} from './types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-1',
    name: 'Hospital Central 24 Horas',
    code: 'HC-01',
    address: 'Av. Corrientes 4550, CABA',
    phone: '+54 11 4862-9900',
    whatsapp: '+54 9 11 3822-9011',
    email: 'contacto@vetsystem.com.ar',
    cuit: '30-71458920-4',
    taxCondition: 'IVA Responsable Inscripto',
  },
  {
    id: 'branch-2',
    name: 'Clínica & Consultorios Norte',
    code: 'CN-02',
    address: 'Av. Maipú 2140, Olivos, Buenos Aires',
    phone: '+54 11 4791-3320',
    whatsapp: '+54 9 11 4455-8812',
    email: 'norte@vetsystem.com.ar',
    cuit: '30-71458920-4',
    taxCondition: 'IVA Responsable Inscripto',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Dr. Martín López',
    email: 'mlopez@vetsystem.com.ar',
    role: 'VETERINARIO',
    licenseNumber: 'MP 8412 - Cirugía & UCI',
    branchId: 'branch-1',
  },
  {
    id: 'user-2',
    name: 'Dra. Carolina Silva',
    email: 'csilva@vetsystem.com.ar',
    role: 'VETERINARIO',
    licenseNumber: 'MP 9520 - Clínica Médica',
    branchId: 'branch-1',
  },
  {
    id: 'user-3',
    name: 'Lic. Gonzalo Rossi',
    email: 'grossi@vetsystem.com.ar',
    role: 'ENFERMERIA',
    branchId: 'branch-1',
  },
  {
    id: 'user-4',
    name: 'Romina Juárez',
    email: 'rjuarez@vetsystem.com.ar',
    role: 'RECEPCION',
    branchId: 'branch-1',
  },
  {
    id: 'user-5',
    name: 'Matías Beltrán',
    email: 'mbeltran@vetsystem.com.ar',
    role: 'CAJA',
    branchId: 'branch-1',
  },
  {
    id: 'user-6',
    name: 'Superadmin Sistema',
    email: 'admin@vetsystem.com.ar',
    role: 'SUPERADMIN',
    branchId: 'branch-1',
  },
];

export const INITIAL_OWNERS: Owner[] = [
  {
    id: 'owner-1',
    firstName: 'Juan',
    lastName: 'Pérez',
    dni: '32.450.812',
    cuit: '20-32450812-3',
    phone: '+54 11 4892-1144',
    whatsapp: '+5491148921144',
    email: 'juan.perez@gmail.com',
    address: 'Av. Libertador 2450, Piso 4B',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1425',
    notes: 'Cliente habitual hace 5 años. Muy atento con la medicación.',
    balance: 0,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'owner-2',
    firstName: 'María',
    lastName: 'Gómez',
    dni: '28.910.433',
    cuit: '27-28910433-8',
    phone: '+54 11 5520-9931',
    whatsapp: '+5491155209931',
    email: 'maria.gomez@hotmail.com',
    address: 'Calle Juncal 1820',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1125',
    notes: 'Propietaria de felinos.',
    balance: 0,
    createdAt: '2024-02-10T14:30:00Z',
  },
  {
    id: 'owner-3',
    firstName: 'Carlos',
    lastName: 'Rossi',
    dni: '25.334.120',
    cuit: '20-25334120-4',
    phone: '+54 11 6122-8700',
    whatsapp: '+5491161228700',
    email: 'carlos.rossi@outlook.com',
    address: 'Juramento 3100',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1428',
    notes: 'Prefiere ser contactado por WhatsApp.',
    balance: -15000, // Saldo deudor pendiente
    createdAt: '2024-03-01T11:00:00Z',
  },
  {
    id: 'owner-4',
    firstName: 'Lucía',
    lastName: 'Navarro',
    dni: '36.882.100',
    phone: '+54 11 4780-5544',
    whatsapp: '+5491147805544',
    email: 'lucia.navarro@yahoo.com.ar',
    address: 'Av. Cabildo 1500',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1426',
    notes: 'Cuenta al día.',
    balance: 0,
    createdAt: '2024-04-12T16:00:00Z',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    clinicalRecordNumber: 'HC-2024-0012',
    name: 'Toby',
    species: 'CANINO',
    breed: 'Golden Retriever',
    sex: 'MACHO',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2016-04-10',
    calculatedAge: '8 años',
    weight: 28.4,
    color: 'Dorado claro',
    microchip: '981020002849102',
    photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&auto=format&fit=crop&q=80',
    ownerId: 'owner-1',
    primaryVetId: 'user-1',
    status: 'INTERNADO',
    alerts: [
      { type: 'ALERGIA', description: 'Alergia conocida a Penicilina / Aminopenicilinas' },
      { type: 'CARDIOPATIA', description: 'Leve soplo sistólico mitral grado II/VI compensado' },
      { type: 'RIESGO_ANESTESICO', description: 'Riesgo ASA III por cuadro hemodinámico actual' },
    ],
    branchId: 'branch-1',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'pat-2',
    clinicalRecordNumber: 'HC-2024-0045',
    name: 'Luna',
    species: 'FELINO',
    breed: 'Siamés Tradicional',
    sex: 'HEMBRA',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2021-08-15',
    calculatedAge: '3 años',
    weight: 3.8,
    color: 'Seal Point',
    microchip: '981020003310921',
    photoUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&auto=format&fit=crop&q=80',
    ownerId: 'owner-2',
    primaryVetId: 'user-2',
    status: 'ACTIVO',
    alerts: [
      { type: 'AGRESIVO', description: 'Estrés marcado en consulta felina. Manejo cat-friendly suave.' },
    ],
    branchId: 'branch-1',
    createdAt: '2024-02-10T14:40:00Z',
  },
  {
    id: 'pat-3',
    clinicalRecordNumber: 'HC-2024-0089',
    name: 'Rocco',
    species: 'CANINO',
    breed: 'Ovejero Alemán',
    sex: 'MACHO',
    reproductiveStatus: 'ENTERO',
    birthDate: '2018-11-20',
    calculatedAge: '6 años',
    weight: 35.2,
    color: 'Negro y Fuego',
    microchip: '981020009948123',
    photoUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400&auto=format&fit=crop&q=80',
    ownerId: 'owner-3',
    primaryVetId: 'user-1',
    status: 'ACTIVO',
    alerts: [
      { type: 'MEDICACION_CRONICA', description: 'Condroprotectores y Omega 3 por displasia coxofemoral' },
    ],
    branchId: 'branch-1',
    createdAt: '2024-03-01T11:20:00Z',
  },
  {
    id: 'pat-4',
    clinicalRecordNumber: 'HC-2024-0104',
    name: 'Mía',
    species: 'CANINO',
    breed: 'Caniche Toy',
    sex: 'HEMBRA',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2013-05-12',
    calculatedAge: '11 años',
    weight: 4.2,
    color: 'Blanco',
    photoUrl: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eab2?w=400&auto=format&fit=crop&q=80',
    ownerId: 'owner-4',
    primaryVetId: 'user-2',
    status: 'ACTIVO',
    alerts: [
      { type: 'CARDIOPATIA', description: 'Endocardiosis mitral crónica estadio B2. Recibe Pimobendan.' },
      { type: 'RENAL', description: 'Control de creatinina y urea cada 3 meses.' },
    ],
    branchId: 'branch-1',
    createdAt: '2024-04-12T16:20:00Z',
  },
  {
    id: 'pat-5',
    clinicalRecordNumber: 'HC-2024-0130',
    name: 'Thor',
    species: 'FELINO',
    breed: 'Europeo Común',
    sex: 'MACHO',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2020-03-10',
    calculatedAge: '4 años',
    weight: 5.4,
    color: 'Atigrado Gris',
    photoUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&auto=format&fit=crop&q=80',
    ownerId: 'owner-2',
    primaryVetId: 'user-1',
    status: 'INTERNADO',
    alerts: [
      { type: 'AISLAMIENTO', description: 'Sonda uretral colocada. Monitoreo estricto de diuresis.' },
    ],
    branchId: 'branch-1',
    createdAt: '2024-05-02T09:00:00Z',
  },
];

export const INITIAL_PROBLEMS: PatientProblem[] = [
  {
    id: 'prob-1',
    patientId: 'pat-1',
    title: 'Gastroenteritis Hemorrágica Aguda',
    description: 'Cuadro de inicio súbito con vómitos biliosos y deposiciones diarreicas sanguinolentas.',
    status: 'ACTIVO',
    onsetDate: '2024-08-17',
    vetName: 'Dr. Martín López',
  },
  {
    id: 'prob-2',
    patientId: 'pat-1',
    title: 'Deshidratación Moderada (7-8%)',
    description: 'TLLC 3 seg, pliegue cutáneo disminuido, mucosas secas.',
    status: 'ACTIVO',
    onsetDate: '2024-08-17',
    vetName: 'Dr. Martín López',
  },
  {
    id: 'prob-3',
    patientId: 'pat-1',
    title: 'Otitis Externa Bilateral',
    description: 'Episodio resuelto con gotas óticas antibióticas/antiinflamatorias.',
    status: 'RESUELTO',
    onsetDate: '2024-02-10',
    resolvedDate: '2024-02-25',
    vetName: 'Dra. Carolina Silva',
  },
  {
    id: 'prob-4',
    patientId: 'pat-4',
    title: 'Enfermedad Degenerativa Valvular Mitral (B2)',
    description: 'Soplo holosistólico III/VI en foco mitral apexiano izquierdo.',
    status: 'CRONICO',
    onsetDate: '2023-11-05',
    vetName: 'Dra. Carolina Silva',
  },
];

export const INITIAL_VITALS: VitalSigns[] = [
  {
    id: 'vit-1',
    patientId: 'pat-1',
    recordedAt: '2024-08-18T12:00:00Z',
    recordedBy: 'Lic. Gonzalo Rossi',
    weight: 28.4,
    temperature: 39.1,
    heartRate: 118,
    respiratoryRate: 28,
    systolicBP: 115,
    diastolicBP: 72,
    meanBP: 86,
    spo2: 98,
    bloodGlucose: 104,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 2,
    hydrationStatus: 'DESHIDRATACION_5',
    consciousnessLevel: 'ALERTA',
    painScale: 2,
    bodyConditionScore: '5/9',
    notes: 'Paciente más animado, respondió favorablemente a la fluidoterapia.',
  },
  {
    id: 'vit-2',
    patientId: 'pat-1',
    recordedAt: '2024-08-18T08:00:00Z',
    recordedBy: 'Lic. Gonzalo Rossi',
    weight: 28.1,
    temperature: 39.4,
    heartRate: 130,
    respiratoryRate: 34,
    systolicBP: 105,
    diastolicBP: 65,
    meanBP: 78,
    spo2: 97,
    bloodGlucose: 96,
    mucousMembranes: 'PALIDAS',
    capillaryRefillTime: 3,
    hydrationStatus: 'DESHIDRATACION_8',
    consciousnessLevel: 'DEPRIMIDO',
    painScale: 4,
    bodyConditionScore: '5/9',
    notes: 'Dolor moderado a la palpación epigástrica. Mucosas secas.',
  },
  {
    id: 'vit-3',
    patientId: 'pat-1',
    recordedAt: '2024-08-17T20:00:00Z',
    recordedBy: 'Dr. Martín López',
    weight: 28.0,
    temperature: 39.6,
    heartRate: 140,
    respiratoryRate: 38,
    systolicBP: 98,
    diastolicBP: 58,
    meanBP: 71,
    spo2: 96,
    bloodGlucose: 92,
    mucousMembranes: 'PALIDAS',
    capillaryRefillTime: 3,
    hydrationStatus: 'DESHIDRATACION_8',
    consciousnessLevel: 'DEPRIMIDO',
    painScale: 5,
    bodyConditionScore: '5/9',
    notes: 'Ingreso a internación de urgencia por guardia.',
  },
];

export const INITIAL_CONSULTATIONS: Consultation[] = [
  {
    id: 'cons-1',
    patientId: 'pat-1',
    vetId: 'user-1',
    vetName: 'Dr. Martín López',
    branchId: 'branch-1',
    dateTime: '2024-08-17T19:30:00Z',
    reason: 'Vómitos frecuentes (6 episodios) y diarrea con sangre fresca',
    anamnesis: 'Propietario refiere que Toby comenzó hace 18 horas con decaimiento, rechazo del alimento, vómitos espumosos y luego biliosos. En las últimas horas tuvo 3 deposiciones diarreicas de aspecto achocolatado fétido con estrías sanguinolentas.',
    vitalSigns: {
      id: 'vit-cons-1',
      patientId: 'pat-1',
      recordedAt: '2024-08-17T19:40:00Z',
      recordedBy: 'Dr. Martín López',
      weight: 28.0,
      temperature: 39.6,
      heartRate: 140,
      respiratoryRate: 38,
      systolicBP: 98,
      diastolicBP: 58,
      meanBP: 71,
      spo2: 96,
      mucousMembranes: 'PALIDAS',
      capillaryRefillTime: 3,
      hydrationStatus: 'DESHIDRATACION_8',
      painScale: 5,
    },
    physicalExam: {
      general: 'Decaído, marcha lenta pero sin ataxia.',
      skinAndCoat: 'Pliegue cutáneo persistente >3 seg. Manto sin ectoparásitos.',
      eyes: 'Globos oculares levemente enoftálmicos por deshidratación.',
      ears: 'Conductos auditivos limpios, sin secreción.',
      oralCavity: 'Mucosas pálidas y pegajosas. TLLC 3 segundos. Sin cuerpos extraños sublinguales.',
      lymphNodes: 'Ganglios periféricos normales, sin adenomegalias.',
      cardiovascular: 'Taquicardia sinusal rítmica. Soplo sistólico apical izquierdo II/VI conocido. Pulsos femorales débiles pero sincrónicos.',
      respiratory: 'Taquipnea compensatoria. Campos pulmonares limpios a la auscultación.',
      digestive: 'Abdomen tenso, dolor marcado a la palpación epigástrica y mesogástrica. Asas intestinales con presencia de gas y líquido. Región perianal manchada con restos hemorrágicos.',
      urinary: 'Vejiga pletórica normodistendida.',
      reproductive: 'Macho castrado, orificio prepucial limpio.',
      musculoskeletal: 'Sin claudicaciones aparentes.',
      neurological: 'Reflejos normales, nivel de conciencia alerta-deprimido.',
      isNormalPresetApplied: false,
    },
    soap: {
      id: 'soap-1',
      consultationId: 'cons-1',
      patientId: 'pat-1',
      subjective: 'Canino macho castrado de 8 años con vómitos incoercibles y enteritis hemorrágica de 18 hs de evolución.',
      objective: 'T 39.6°C, FC 140 lpm, FR 38 rpm, PA 98/58, TLLC 3s, Mucosas pálidas secas, Deshidratación estimada 8%. Abdomen agudo doloroso.',
      assessment: '1. Síndrome de Gastroenteritis Hemorrágica Aguda (SGHA/HGE). 2. Deshidratación moderada/severa con compromiso hemodinámico. 3. Descarte de cuerpo extraño / intususcepción / pancreatitis.',
      plan: '1. Internación inmediata en UCI. 2. Cateterización venosa periférica (Catéter 20G). 3. Fluidoterapia de rescate con Ringer Lactato a 85 ml/h. 4. Hemograma + Bioquímica + Ecografía abdominal urgente. 5. Maropitant 1mg/kg SC + Ceftriaxona 25mg/kg IV c/12h + Ranitidina 2mg/kg IV + Tramadol 2mg/kg IV.',
      createdAt: '2024-08-17T20:15:00Z',
      vetName: 'Dr. Martín López',
    },
    diagnoses: ['Gastroenteritis Hemorrágica Aguda', 'Deshidratación 8%'],
    differentialDiagnoses: ['Pancreatitis aguda', 'Cuerpo extraño digestivo', 'Parvovirosis / Giardiasis'],
    treatmentPlan: 'Internación en UCI con fluidoterapia continua y terapia antiemética/antibiótica endovenosa.',
    prescriptions: [
      {
        id: 'presc-1',
        medicationName: 'Ceftriaxona 1g Frasco Ampolla',
        presentation: 'Vial inyectable IV',
        dose: '500 mg (20 mg/kg)',
        route: 'IV',
        frequency: 'Cada 12 horas',
        duration: 'Durante 3 días de internación',
        instructions: 'Diluir lentamente en microgotero.',
      },
      {
        id: 'presc-2',
        medicationName: 'Maropitant (Cerenia) 10 mg/ml',
        presentation: 'Inyectable SC/IV',
        dose: '28 mg (1 mg/kg)',
        route: 'SC',
        frequency: 'Cada 24 horas',
        duration: 'Durante 3 días',
        instructions: 'Aplicar frío para reducir molestia.',
      },
      {
        id: 'presc-3',
        medicationName: 'Tramadol 50 mg/ml',
        presentation: 'Inyectable IV lento',
        dose: '50 mg (2 mg/kg)',
        route: 'IV',
        frequency: 'Cada 8 horas',
        duration: 'Según escala de dolor',
        instructions: 'Administrar diluido en 10 ml de fisiológico en 15 min.',
      },
    ],
    orderedStudies: ['Hemograma Completo', 'Perfil Bioquímico Renal/Hepático', 'Ecografía Abdominal Completa'],
    requiresHospitalization: true,
    status: 'FINALIZADA',
  },
];

export const INITIAL_HOSPITALIZATIONS: Hospitalization[] = [
  {
    id: 'hosp-1',
    patientId: 'pat-1',
    vetInChargeId: 'user-1',
    vetInChargeName: 'Dr. Martín López',
    sector: 'UCI',
    kennelNumber: 'UCI-02',
    admittedAt: '2024-08-17T20:00:00Z',
    primaryDiagnosis: 'Gastroenteritis hemorrágica aguda - Deshidratación 8%',
    priority: 'CRITICO',
    fluidTherapy: {
      isActive: true,
      solutionType: 'Ringer Lactato + KCl 20 mEq/L',
      volumeTotalMl: 2000,
      rateMlPerHour: 85,
      dropsPerMinute: 28,
      infusionRoute: 'IV',
      startedAt: '2024-08-17T20:30:00Z',
      pumpNumber: 'Bomba Volumétrica #04',
      additives: 'KCl 20 mEq/L + Metoclopramida 1 mg/kg/día CRI',
      prescribedBy: 'Dr. Martín López',
    },
    feeding: {
      dietType: 'NPO_AYUNO',
      foodBrand: 'Ayuno estricto primeras 24hs post cese de vómitos',
      amountGramsOrMl: 0,
      frequency: 'Ayuno hasta evaluación matutina',
      tolerance: 'EXCELENTE',
    },
    eliminations: [
      {
        id: 'elim-1',
        timestamp: '2024-08-18T11:15:00Z',
        type: 'MICCION',
        amount: 'MODERADA',
        aspect: 'Orina amarilla ámbar clara, densidad normal.',
        registeredBy: 'Lic. Gonzalo Rossi',
      },
      {
        id: 'elim-2',
        timestamp: '2024-08-18T06:30:00Z',
        type: 'VOMITO',
        amount: 'ESCASA',
        aspect: 'Líquido gástrico claro espumoso con mucosidad.',
        registeredBy: 'Lic. Gonzalo Rossi',
      },
      {
        id: 'elim-3',
        timestamp: '2024-08-17T22:40:00Z',
        type: 'DIARREA',
        amount: 'MODERADA',
        aspect: 'Heces líquidas achocolatadas con restos de sangre digerida.',
        registeredBy: 'Lic. Gonzalo Rossi',
      },
    ],
    medications: [
      {
        id: 'med-sch-1',
        hospitalizationId: 'hosp-1',
        patientId: 'pat-1',
        drugName: 'Ceftriaxona 500 mg',
        dose: '500 mg',
        route: 'IV',
        frequencyHours: 12,
        scheduledTime: '20:00',
        status: 'PROXIMA',
        productId: 'prod-1',
        notes: 'Dosis nocturna',
      },
      {
        id: 'med-sch-2',
        hospitalizationId: 'hosp-1',
        patientId: 'pat-1',
        drugName: 'Ceftriaxona 500 mg',
        dose: '500 mg',
        route: 'IV',
        frequencyHours: 12,
        scheduledTime: '08:00',
        status: 'REALIZADA',
        administeredAt: '2024-08-18T08:05:00Z',
        administeredBy: 'Lic. Gonzalo Rossi',
        productId: 'prod-1',
        notes: 'Administrado sin incidentes.',
      },
      {
        id: 'med-sch-3',
        hospitalizationId: 'hosp-1',
        patientId: 'pat-1',
        drugName: 'Maropitant (Cerenia) 28 mg',
        dose: '28 mg',
        route: 'SC',
        frequencyHours: 24,
        scheduledTime: '16:30',
        status: 'PROXIMA',
        productId: 'prod-2',
      },
      {
        id: 'med-sch-4',
        hospitalizationId: 'hosp-1',
        patientId: 'pat-1',
        drugName: 'Ranitidina / Omeprazol 50 mg',
        dose: '50 mg',
        route: 'IV',
        frequencyHours: 8,
        scheduledTime: '14:00',
        status: 'REALIZADA',
        administeredAt: '2024-08-18T14:10:00Z',
        administeredBy: 'Lic. Gonzalo Rossi',
        productId: 'prod-4',
      },
      {
        id: 'med-sch-5',
        hospitalizationId: 'hosp-1',
        patientId: 'pat-1',
        drugName: 'Tramadol 50 mg',
        dose: '50 mg',
        route: 'IV lento',
        frequencyHours: 8,
        scheduledTime: '22:00',
        status: 'PROGRAMADA',
        productId: 'prod-3',
      },
    ],
    tasks: [
      {
        id: 'task-1',
        time: '14:00',
        title: 'Medicación: Protector gástrico IV',
        type: 'MEDICACION',
        isCompleted: true,
        completedAt: '2024-08-18T14:10:00Z',
        completedBy: 'Lic. Gonzalo Rossi',
      },
      {
        id: 'task-2',
        time: '16:00',
        title: 'Control de Signos Vitales y Escala de Dolor',
        type: 'SIGNOS',
        isCompleted: false,
      },
      {
        id: 'task-3',
        time: '16:30',
        title: 'Administración de Antiemético (Maropitant)',
        type: 'MEDICACION',
        isCompleted: false,
      },
      {
        id: 'task-4',
        time: '18:00',
        title: 'Revisión de vía permeable y ritmo de bomba de fluidos',
        type: 'FLUIDOS',
        isCompleted: false,
      },
    ],
    hourlySheet: [
      {
        id: 'sheet-1',
        timestamp: '08:00',
        temperature: 39.4,
        heartRate: 130,
        respiratoryRate: 34,
        bloodPressure: '105/65',
        spo2: 97,
        glucose: 96,
        painLevel: 4,
        fluidStatus: 'Bomba 85 ml/h activa',
        medsAdministered: ['Ceftriaxona 500mg IV'],
        feeding: 'NPO (Ayuno)',
        eliminations: 'Vómito gástrico leve',
        observations: 'Paciente decaído. Pliegue cutáneo mejora lentamente.',
        staffName: 'Lic. Gonzalo Rossi',
      },
      {
        id: 'sheet-2',
        timestamp: '10:00',
        temperature: 39.2,
        heartRate: 122,
        respiratoryRate: 30,
        bloodPressure: '110/68',
        spo2: 98,
        glucose: 102,
        painLevel: 3,
        fluidStatus: 'Bomba 85 ml/h activa',
        feeding: 'NPO (Ayuno)',
        eliminations: 'Sin diarreas nuevas',
        observations: 'Comienza a levantar la cabeza y mira al personal.',
        staffName: 'Lic. Gonzalo Rossi',
      },
      {
        id: 'sheet-3',
        timestamp: '12:00',
        temperature: 39.1,
        heartRate: 118,
        respiratoryRate: 28,
        bloodPressure: '115/72',
        spo2: 98,
        glucose: 104,
        painLevel: 2,
        fluidStatus: 'Bomba 85 ml/h activa',
        medsAdministered: ['Ranitidina 50mg IV'],
        feeding: 'NPO (Ayuno)',
        eliminations: 'Micción abundante clara',
        observations: 'Buena perfusión renal. TLLC 2 seg.',
        staffName: 'Lic. Gonzalo Rossi',
      },
    ],
    intervalHours: 2,
    nextMedicationTime: '16:30',
    nextVitalsTime: '16:00',
    status: 'ACTIVA',
    branchId: 'branch-1',
  },
  {
    id: 'hosp-2',
    patientId: 'pat-5',
    vetInChargeId: 'user-1',
    vetInChargeName: 'Dr. Martín López',
    sector: 'FELINOS',
    kennelNumber: 'FEL-01',
    admittedAt: '2024-08-18T09:30:00Z',
    primaryDiagnosis: 'Obstrucción Uretral Felina (Sindrome Urológico Felino)',
    priority: 'PRIORITARIO',
    fluidTherapy: {
      isActive: true,
      solutionType: 'Solución Fisiológica 0.9%',
      volumeTotalMl: 500,
      rateMlPerHour: 15,
      dropsPerMinute: 5,
      infusionRoute: 'IV',
      startedAt: '2024-08-18T10:00:00Z',
      pumpNumber: 'Bomba #02',
      prescribedBy: 'Dr. Martín López',
    },
    feeding: {
      dietType: 'ORAL',
      foodBrand: 'Alimento húmedo urinario',
      amountGramsOrMl: 50,
      frequency: 'Cada 8 hs',
      tolerance: 'PARCIAL',
    },
    eliminations: [
      {
        id: 'elim-thor-1',
        timestamp: '2024-08-18T11:00:00Z',
        type: 'MICCION',
        amount: 'ABUNDANTE',
        aspect: 'Orina recolectada en bolsa cerrada, ligeramente hematúrica.',
        registeredBy: 'Lic. Gonzalo Rossi',
      },
    ],
    medications: [
      {
        id: 'med-thor-1',
        hospitalizationId: 'hosp-2',
        patientId: 'pat-5',
        drugName: 'Buprenorfina 0.02 mg/kg',
        dose: '0.1 mg',
        route: 'SC',
        frequencyHours: 8,
        scheduledTime: '18:00',
        status: 'PROGRAMADA',
      },
      {
        id: 'med-thor-2',
        hospitalizationId: 'hosp-2',
        patientId: 'pat-5',
        drugName: 'Prazosina 0.5 mg',
        dose: '0.5 mg',
        route: 'ORAL',
        frequencyHours: 12,
        scheduledTime: '20:00',
        status: 'PROGRAMADA',
      },
    ],
    tasks: [
      {
        id: 'task-thor-1',
        time: '15:00',
        title: 'Medición de diuresis horaria (ml/kg/h)',
        type: 'FLUIDOS',
        isCompleted: false,
      },
    ],
    hourlySheet: [
      {
        id: 'sheet-thor-1',
        timestamp: '10:00',
        temperature: 38.4,
        heartRate: 160,
        respiratoryRate: 32,
        bloodPressure: '120/80',
        spo2: 99,
        glucose: 110,
        painLevel: 3,
        fluidStatus: '15 ml/h',
        observations: 'Sonda uretral normoposicionada permeable.',
        staffName: 'Lic. Gonzalo Rossi',
      },
    ],
    intervalHours: 4,
    nextMedicationTime: '18:00',
    nextVitalsTime: '16:00',
    status: 'ACTIVA',
    branchId: 'branch-1',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    code: 'MED-001',
    barcode: '7790012345678',
    commercialName: 'Ceftriaxona 1g Inyectable',
    activeIngredient: 'Ceftriaxona Sódica',
    category: 'MEDICAMENTO',
    concentration: '1000 mg / ampolla',
    presentation: 'Frasco ampolla con solvente 10ml',
    laboratory: 'Lab Richmond Vet',
    costPrice: 4200,
    salePrice: 8500,
    currentStock: 14,
    minStock: 5,
    currentBatch: 'LT-9821',
    expirationDate: '2026-11-30',
    supplier: 'Droguería Veterinaria Sur',
    branchId: 'branch-1',
  },
  {
    id: 'prod-2',
    code: 'MED-002',
    barcode: '7790012345685',
    commercialName: 'Cerenia Inyectable 10mg/ml',
    activeIngredient: 'Maropitant Citrato',
    category: 'MEDICAMENTO',
    concentration: '10 mg/ml',
    presentation: 'Frasco ampolla 20 ml',
    laboratory: 'Zoetis',
    costPrice: 28000,
    salePrice: 45000,
    currentStock: 3,
    minStock: 2,
    currentBatch: 'ZO-4410',
    expirationDate: '2025-10-15',
    supplier: 'Distribuidora Zoetis',
    branchId: 'branch-1',
  },
  {
    id: 'prod-3',
    code: 'MED-003',
    barcode: '7790012345692',
    commercialName: 'Tramadol Clorhidrato 50mg/ml',
    activeIngredient: 'Tramadol HCl',
    category: 'MEDICAMENTO',
    concentration: '50 mg/ml',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'John Martin',
    costPrice: 7500,
    salePrice: 14200,
    currentStock: 8,
    minStock: 4,
    currentBatch: 'JM-7712',
    expirationDate: '2026-06-30',
    supplier: 'Droguería Veterinaria Sur',
    branchId: 'branch-1',
  },
  {
    id: 'prod-4',
    code: 'MED-004',
    barcode: '7790012345708',
    commercialName: 'Solución Ringer Lactato 500ml',
    activeIngredient: 'Electrolitos balanceados',
    category: 'DESCARTABLE',
    concentration: '500 ml',
    presentation: 'Sachet colapsable estéril',
    laboratory: 'B. Braun / Rivero',
    costPrice: 1800,
    salePrice: 4200,
    currentStock: 35,
    minStock: 15,
    currentBatch: 'RL-1094',
    expirationDate: '2027-02-28',
    supplier: 'Insumos Médicos SRL',
    branchId: 'branch-1',
  },
  {
    id: 'prod-5',
    code: 'VAC-001',
    barcode: '7790012345715',
    commercialName: 'Nobivac DHPPI+L (Séxtuple)',
    activeIngredient: 'Virus atenuados Distemper, Adenovirus, Parvovirus, Leptospira',
    category: 'VACUNA',
    concentration: '1 dosis (1 ml)',
    presentation: 'Frasco ampolla con liofilizado y diluyente',
    laboratory: 'MSD Animal Health',
    costPrice: 9500,
    salePrice: 19500,
    currentStock: 22,
    minStock: 10,
    currentBatch: 'MSD-8841',
    expirationDate: '2025-12-31',
    supplier: 'Distribuidora Biológicos',
    branchId: 'branch-1',
  },
  {
    id: 'prod-6',
    code: 'VAC-002',
    barcode: '7790012345722',
    commercialName: 'Nobivac Rabia (Antirrábica)',
    activeIngredient: 'Virus rábico inactivado',
    category: 'VACUNA',
    concentration: '1 dosis (1 ml)',
    presentation: 'Frasco ampolla 1 ml',
    laboratory: 'MSD Animal Health',
    costPrice: 4800,
    salePrice: 11000,
    currentStock: 18,
    minStock: 8,
    currentBatch: 'RB-3021',
    expirationDate: '2026-04-30',
    supplier: 'Distribuidora Biológicos',
    branchId: 'branch-1',
  },
  {
    id: 'prod-7',
    code: 'MED-005',
    barcode: '7790012345739',
    commercialName: 'Pimobendan 5mg (Cardisure)',
    activeIngredient: 'Pimobendan',
    category: 'MEDICAMENTO',
    concentration: '5 mg',
    presentation: 'Caja x 100 comprimidos masticables',
    laboratory: 'Eurovet / Dechra',
    costPrice: 42000,
    salePrice: 68000,
    currentStock: 2, // ALERTA BAJO STOCK
    minStock: 3,
    currentBatch: 'EU-1109',
    expirationDate: '2025-08-30',
    supplier: 'Droguería Veterinaria Sur',
    branchId: 'branch-1',
  },
];

export const INITIAL_LAB_ORDERS: LaboratoryOrder[] = [
  {
    id: 'lab-1',
    orderNumber: 'LAB-2024-0089',
    patientId: 'pat-1',
    testType: 'HEMOGRAMA_COMPLETO',
    requestedBy: 'Dr. Martín López',
    requestedAt: '2024-08-17T20:15:00Z',
    sampleCollectedAt: '2024-08-17T20:30:00Z',
    resultsReadyAt: '2024-08-17T21:45:00Z',
    status: 'FINALIZADO',
    results: [
      { parameter: 'Hematocrito', value: 38.5, unit: '%', referenceRange: '37 - 55' },
      { parameter: 'Hemoglobina', value: 12.8, unit: 'g/dL', referenceRange: '12 - 18' },
      { parameter: 'Glóbulos Blancos (Leucocitos)', value: 16800, unit: '/uL', referenceRange: '6.000 - 17.000', isAbnormal: false },
      { parameter: 'Neutrófilos en cayado (Bandas)', value: 850, unit: '/uL', referenceRange: '0 - 300', isAbnormal: true },
      { parameter: 'Plaquetas', value: 240000, unit: '/uL', referenceRange: '200.000 - 500.000' },
      { parameter: 'Urea Sanguínea', value: 42, unit: 'mg/dL', referenceRange: '20 - 50' },
      { parameter: 'Creatinina', value: 1.1, unit: 'mg/dL', referenceRange: '0.5 - 1.4' },
      { parameter: 'ALT (GPT)', value: 58, unit: 'UI/L', referenceRange: '10 - 80' },
      { parameter: 'Fosfatasa Alcalina (ALP)', value: 110, unit: 'UI/L', referenceRange: '20 - 150' },
      { parameter: 'Proteínas Totales', value: 6.8, unit: 'g/dL', referenceRange: '5.5 - 7.5' },
    ],
    diagnosticReport: 'Ligero desvío a la izquierda con neutrofilia relativa reactiva. Función renal y hepática conservada al momento de la admisión.',
    conclusions: 'Compatible con proceso inflamatorio/infeccioso gastrointestinal agudo sin compromiso renal por deshidratación severa.',
  },
];

export const INITIAL_IMAGING: ImagingStudy[] = [
  {
    id: 'img-1',
    studyNumber: 'IMG-2024-0044',
    patientId: 'pat-1',
    modality: 'ECOGRAFIA',
    region: 'Abdomen Completo (Énfasis Gastrointestinal)',
    requestedBy: 'Dr. Martín López',
    performedBy: 'Dra. Carolina Silva',
    date: '2024-08-17T21:00:00Z',
    report: 'Hígado y vesícula biliar de ecoestructura y tamaño normal. Bazo homogéneo sin lesiones focales. Riñones simétricos con buena relación córtico-medular. Vejiga urinaria anecoica. ESTÓMAGO: Pared engrosada (5.4 mm, ref <4mm) con estratificación conservada, presencia de fluido intraluminal. INTESTINO: Asas de duodeno y yeyuno con contenido mucoso-líquido, peristalsis disminuida. No se observan imágenes compatibles con cuerpo extraño obstructivo ni intususcepción.',
    conclusion: 'Signos ecográficos compatibles con gastritis y enteritis aguda difusa sin evidencia de obstrucción mecánica.',
    images: [
      {
        id: 'img-file-1',
        url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&auto=format&fit=crop&q=80',
        caption: 'Corte ecográfico longitudinal de pared gástrica engrosada 5.4mm',
      },
    ],
    status: 'INFORMADO',
  },
];

export const INITIAL_SURGERIES: SurgeryRecord[] = [
  {
    id: 'surg-1',
    patientId: 'pat-3',
    procedureName: 'Limpieza Dental por Ultrasonido + Exéresis Nódulo Cutáneo',
    surgeonName: 'Dr. Martín López',
    assistantName: 'Lic. Gonzalo Rossi',
    anesthetistName: 'Dra. Carolina Silva',
    branchId: 'branch-1',
    date: '2024-08-19',
    startTime: '09:00',
    endTime: '10:30',
    preOpAssessment: {
      asaGrade: 'II',
      fastingHours: 10,
      labReviewed: true,
      risksAlerts: 'Monitorear presión arterial por edad y peso (35.2 kg).',
    },
    anesthesiaProtocol: {
      premedication: 'Acepromacina 0.02 mg/kg + Morfina 0.3 mg/kg IM',
      induction: 'Propofol 4 mg/kg IV a efecto',
      maintenance: 'Isoflurano 1.5% en Oxígeno 100% (Circuito circular con re-inhalación)',
      analgesia: 'Meloxicam 0.2 mg/kg SC post quirúrgico',
      monitoringPoints: [
        { time: '09:15', heartRate: 90, respiratoryRate: 14, systolicBP: 120, diastolicBP: 75, spo2: 99, etco2: 38, temperature: 38.0, isoOrSevoPercent: 1.8, oxygenFlowLMin: 1.5, fluidsGivenMl: 150 },
        { time: '09:30', heartRate: 86, respiratoryRate: 12, systolicBP: 115, diastolicBP: 70, spo2: 99, etco2: 40, temperature: 37.8, isoOrSevoPercent: 1.5, oxygenFlowLMin: 1.5, fluidsGivenMl: 250 },
        { time: '09:45', heartRate: 88, respiratoryRate: 14, systolicBP: 118, diastolicBP: 72, spo2: 99, etco2: 39, temperature: 37.6, isoOrSevoPercent: 1.5, oxygenFlowLMin: 1.5, fluidsGivenMl: 350 },
      ],
      milestones: {
        inductionTime: '09:05',
        intubationTime: '09:10',
        incisionTime: '09:20',
        sutureTime: '10:15',
        extubationTime: '10:25',
        recoveryTime: '10:45',
      },
    },
    surgicalTechnique: 'Detartraje supragingival y subgingival con scaler ultrasónico, pulido con pasta profiláctica. Incisión elíptica perilesional en flanco derecho para remover nódulo de 1.5 cm con margen libre. Cierre en dos planos con Nylon 3-0.',
    findings: 'Gingivitis moderada, sin movilidad dental que requiriera exodoncia. Nódulo bien delimitado enviado a biopsia.',
    materialsUsed: [
      { productId: 'prod-4', name: 'Solución Ringer Lactato', quantity: 1 },
    ],
    postOpOrders: 'Collar isabelino por 10 días, curación con Clorhexidina 0.5% bid, antibiótico Cefalexina 500mg c/12h x 7 días.',
    status: 'PROGRAMADA',
  },
];

export const INITIAL_VACCINATIONS: VaccinationRecord[] = [
  {
    id: 'vac-1',
    patientId: 'pat-1',
    vaccineName: 'Séxtuple Canina (DHPPI+L)',
    manufacturer: 'MSD Animal Health',
    batchNumber: 'MSD-8841',
    expirationDate: '2025-12-31',
    administeredDate: '2024-04-10',
    administeredBy: 'Dr. Martín López',
    vetLicense: 'MP 8412',
    nextDueDate: '2025-04-10',
    certificateGenerated: true,
  },
  {
    id: 'vac-2',
    patientId: 'pat-1',
    vaccineName: 'Antirrábica Canina Oficial',
    manufacturer: 'MSD Animal Health',
    batchNumber: 'RB-3021',
    expirationDate: '2026-04-30',
    administeredDate: '2024-04-10',
    administeredBy: 'Dr. Martín López',
    vetLicense: 'MP 8412',
    nextDueDate: '2025-04-10',
    certificateGenerated: true,
  },
  {
    id: 'vac-3',
    patientId: 'pat-2',
    vaccineName: 'Triple Felina (Rinotraqueítis, Calicivirus, Panleucopenia)',
    manufacturer: 'Zoetis Felocell 3',
    batchNumber: 'ZT-9902',
    expirationDate: '2025-09-30',
    administeredDate: '2023-09-15',
    administeredBy: 'Dra. Carolina Silva',
    vetLicense: 'MP 9520',
    nextDueDate: '2024-09-15', // Próxima a vencer
    certificateGenerated: true,
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'app-1',
    patientId: 'pat-2',
    ownerId: 'owner-2',
    vetId: 'user-2',
    branchId: 'branch-1',
    consultingRoom: 'Consultorio 2 (Felino)',
    date: '2024-08-18',
    time: '15:30',
    durationMinutes: 30,
    type: 'VACUNACION',
    reason: 'Refuerzo anual de Triple Felina y control general',
    status: 'CONFIRMADO',
  },
  {
    id: 'app-2',
    patientId: 'pat-3',
    ownerId: 'owner-3',
    vetId: 'user-1',
    branchId: 'branch-1',
    consultingRoom: 'Quirófano 1',
    date: '2024-08-19',
    time: '09:00',
    durationMinutes: 90,
    type: 'CIRUGIA',
    reason: 'Limpieza dental y biopsia de nódulo',
    status: 'RESERVADO',
  },
  {
    id: 'app-3',
    patientId: 'pat-4',
    ownerId: 'owner-4',
    vetId: 'user-2',
    branchId: 'branch-1',
    consultingRoom: 'Consultorio 1',
    date: '2024-08-18',
    time: '16:00',
    durationMinutes: 30,
    type: 'CONTROL',
    reason: 'Control cardiológico trimestral y ajuste de dosis Pimobendan',
    status: 'ESPERANDO',
  },
];

export const INITIAL_TRIAGE: TriageEntry[] = [
  {
    id: 'triage-1',
    patientId: 'pat-4',
    ownerId: 'owner-4',
    arrivedAt: '2024-08-18T15:45:00Z',
    waitTimeMinutes: 15,
    priority: 'PRIORITARIO',
    chiefComplaint: 'Agitación y tos nocturna leve en paciente cardiópata conocida',
    assignedVetId: 'user-2',
    assignedRoom: 'Consultorio 1',
    initialTemp: 38.5,
    initialHeartRate: 155,
    initialMucous: 'Rosadas',
    status: 'EN_ESPERA',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: '0001-00004921',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2024-08-17',
    ownerId: 'owner-1',
    patientId: 'pat-1',
    customerName: 'Juan Pérez',
    customerDniCuit: '32.450.812',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-1', description: 'Consulta de Urgencia en Guardia 24hs', quantity: 1, unitPrice: 22000, subtotal: 22000 },
      { id: 'item-2', description: 'Hemograma Completo + Bioquímica de Guardia', quantity: 1, unitPrice: 18000, subtotal: 18000 },
      { id: 'item-3', description: 'Ecografía Abdominal Completa de Urgencia', quantity: 1, unitPrice: 24000, subtotal: 24000 },
      { id: 'item-4', description: 'Día de Internación en Unidad de Cuidados Intensivos (UCI)', quantity: 1, unitPrice: 45000, subtotal: 45000 },
    ],
    totalAmount: 109000,
    paymentMethod: 'TRANSFERENCIA',
    caeNumber: '74829103948123',
    caeExpirationDate: '2024-08-27',
    branchId: 'branch-1',
  },
];

export const INITIAL_ESTIMATES: Estimate[] = [
  {
    id: 'est-1',
    estimateNumber: 'PRES-2024-019',
    ownerId: 'owner-3',
    patientId: 'pat-3',
    date: '2024-08-10',
    validUntil: '2024-08-25',
    items: [
      { id: 'e-1', description: 'Profilaxis Dental Ultrasónica con Pulido', quantity: 1, unitPrice: 48000, subtotal: 48000 },
      { id: 'e-2', description: 'Cirugía menor: Exéresis nódulo cutáneo', quantity: 1, unitPrice: 35000, subtotal: 35000 },
      { id: 'e-3', description: 'Anestesia inhalatoria y monitoreo multiparamétrico', quantity: 1, unitPrice: 32000, subtotal: 32000 },
      { id: 'e-4', description: 'Estudio Histopatológico (Biopsia)', quantity: 1, unitPrice: 22000, subtotal: 22000 },
    ],
    totalAmount: 137000,
    notes: 'Presupuesto incluye controles posquirúrgicos y retiro de puntos a los 10 días.',
    status: 'ACEPTADO',
  },
];

export const INITIAL_DOCUMENTS: ClinicalDocument[] = [
  {
    id: 'doc-1',
    type: 'CONSENTIMIENTO_INTERNACION',
    title: 'Consentimiento Informado para Hospitalización e Internación en UCI',
    patientId: 'pat-1',
    ownerId: 'owner-1',
    vetName: 'Dr. Martín López',
    createdAt: '2024-08-17T20:10:00Z',
    content: `Por medio del presente documento, yo Juan Pérez, DNI 32.450.812, en mi carácter de propietario/responsable del paciente Toby (Canino Golden Retriever, 8 años, HC-2024-0012), autorizo al equipo médico de VET SYSTEM a internar a dicho paciente en la Unidad de Cuidados Intensivos (UCI), administrar los tratamientos médicos, fluidoterapia endovenosa, extracción de muestras biológicas y procedimientos diagnósticos requeridos para su estabilización hemodinámica.
He sido fehacientemente informado sobre el cuadro de Gastroenteritis Hemorrágica Aguda, los riesgos inherentes al estado clínico y los costos estimados del servicio.`,
    signedByOwnerName: 'Juan Pérez',
    signedByOwnerDni: '32.450.812',
    isSigned: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: '2024-08-18T14:10:00Z',
    userName: 'Lic. Gonzalo Rossi',
    userRole: 'ENFERMERIA',
    action: 'ADMINISTRACION_MEDICACION',
    entity: 'HospitalizationMedication',
    entityId: 'med-sch-4',
    details: 'Administró Ranitidina 50mg IV a paciente Toby (Canil UCI-02).',
  },
  {
    id: 'audit-2',
    timestamp: '2024-08-18T12:00:00Z',
    userName: 'Lic. Gonzalo Rossi',
    userRole: 'ENFERMERIA',
    action: 'REGISTRO_SIGNOS_VITALES',
    entity: 'VitalSigns',
    entityId: 'vit-1',
    details: 'Registró ronda horaria de signos vitales (T 39.1°C, FC 118, PA 115/72).',
  },
  {
    id: 'audit-3',
    timestamp: '2024-08-17T20:00:00Z',
    userName: 'Dr. Martín López',
    userRole: 'VETERINARIO',
    action: 'INGRESO_INTERNACION',
    entity: 'Hospitalization',
    entityId: 'hosp-1',
    details: 'Ingresó paciente Toby a UCI-02 con diagnóstico de Gastroenteritis Hemorrágica.',
  },
];

export const INITIAL_CASH_SESSION: CashRegisterSession = {
  id: 'cash-sess-1',
  branchId: 'branch-1',
  openedAt: '2024-08-18T08:00:00Z',
  openedBy: 'Matías Beltrán',
  initialCash: 50000,
  totalIncomeCash: 45000,
  totalIncomeDigital: 184000,
  totalExpenses: 12000,
  isClosed: false,
};
