import {
  Branch,
  User,
  Owner,
  Patient,
  VitalSigns,
  Consultation,
  Hospitalization,
  SurgeryRecord,
  LaboratoryOrder,
  ImagingStudy,
  VaccinationRecord,
  Product,
  Appointment,
  TriageEntry,
  Invoice,
  Estimate,
  CashRegisterSession,
  ClinicalDocument,
  AuditLog,
  PatientProblem,
  RegulatoryRule,
  ControlledDrugItem,
  ControlledDrugMovement,
  PathologicalWasteRecord,
  Prescription,
  AntimicrobialRecord,
  ClinicalEvolutionEntry,
  ClinicalEncounter,
  ClinicalProcedure,
  EncounterConsumptionItem,
  ServicePriceItem,
} from './types';

// 1. SUCURSAL OFICIAL UNIFICADA - VETERINARIA RANQUEL
export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-1',
    name: 'Veterinaria Ranquel',
    code: 'VR-01',
    address: 'Casa 13, Barrio Militar de Oficiales, Las Lajas, Neuquén (CP 8347)',
    phone: '+54 9 2942 47-7136',
    whatsapp: '+54 9 2942 47-7136',
    email: 'contacto@veterinariaranquel.com.ar',
    cuit: '20-31458920-4',
    taxCondition: 'IVA Responsable Inscripto',
  },
];

// 2. USUARIO MAESTRO - DIRECTOR MÉDICO
export const INITIAL_USERS: User[] = [
  {
    id: 'user-irusta-dir',
    name: 'Dr. Diego Iván Irusta',
    email: 'irusta@gmail.com',
    role: 'DIRECTOR_MEDICO',
    licenseNumber: 'M.P. 502',
    branchId: 'branch-1',
  },
];

// 3. COLECCIONES CLÍNICAS Y TRANSACCIONALES (LIMPIAS PARA USO REAL)
export const INITIAL_OWNERS: Owner[] = [];
export const INITIAL_PATIENTS: Patient[] = [];
export const INITIAL_PROBLEMS: PatientProblem[] = [];
export const INITIAL_VITALS: VitalSigns[] = [];
export const INITIAL_CONSULTATIONS: Consultation[] = [];
export const INITIAL_HOSPITALIZATIONS: Hospitalization[] = [];
export const INITIAL_SURGERIES: SurgeryRecord[] = [];
export const INITIAL_LABS: LaboratoryOrder[] = [];
export const INITIAL_LAB_ORDERS: LaboratoryOrder[] = [];
export const INITIAL_IMAGING: ImagingStudy[] = [];
export const INITIAL_VACCINES: VaccinationRecord[] = [];
export const INITIAL_VACCINATIONS: VaccinationRecord[] = [];
export const INITIAL_APPOINTMENTS: Appointment[] = [];
export const INITIAL_TRIAGE: TriageEntry[] = [];
export const INITIAL_INVOICES: Invoice[] = [];
export const INITIAL_ESTIMATES: Estimate[] = [];
export const INITIAL_DOCUMENTS: ClinicalDocument[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_CONTROLLED_MOVEMENTS: ControlledDrugMovement[] = [];
export const INITIAL_PATHOLOGICAL_WASTE: PathologicalWasteRecord[] = [];
export const INITIAL_PRESCRIPTIONS: Prescription[] = [];
export const INITIAL_ANTIMICROBIAL_RECORDS: AntimicrobialRecord[] = [];
export const INITIAL_CLINICAL_EVOLUTIONS: ClinicalEvolutionEntry[] = [];

// 3.1 ENCOUNTERS, PROCEDIMIENTOS Y CONSUMOS (LIMPIOS PARA USO REAL)
export const INITIAL_ENCOUNTERS: ClinicalEncounter[] = [];
export const INITIAL_PROCEDURES: ClinicalProcedure[] = [];
export const INITIAL_ENCOUNTER_CONSUMPTIONS: EncounterConsumptionItem[] = [];

// 3.2 CATÁLOGO CENTRAL DE PRECIOS DE SERVICIOS
export const INITIAL_SERVICE_PRICES: ServicePriceItem[] = [
  { id: 'srv-1', code: 'SRV-CONS-01', name: 'Consulta Médica General Ambulatoria', category: 'CONSULTA', price: 18000, isBillable: true },
  { id: 'srv-2', code: 'SRV-CONS-02', name: 'Consulta de Guardia / Urgencia', category: 'CONSULTA', price: 28000, isBillable: true },
  { id: 'srv-3', code: 'SRV-HOSP-01', name: 'Día de Internación General (Caniles)', category: 'INTERNACION', price: 35000, isBillable: true },
  { id: 'srv-4', code: 'SRV-HOSP-02', name: 'Día de Internación UCI / Cuidados Críticos', category: 'INTERNACION', price: 65000, isBillable: true },
  { id: 'srv-5', code: 'SRV-LAB-01', name: 'Hemograma Completo con Frotis', category: 'LABORATORIO', price: 14000, isBillable: true },
  { id: 'srv-6', code: 'SRV-LAB-02', name: 'Perfil Bioquímico Renal y Hepático', category: 'LABORATORIO', price: 22000, isBillable: true },
  { id: 'srv-7', code: 'SRV-LAB-03', name: 'Uranálisis Completo con Sedimento', category: 'LABORATORIO', price: 11000, isBillable: true },
  { id: 'srv-8', code: 'SRV-IMG-01', name: 'Radiografía Digital (2 Proyecciones)', category: 'IMAGENES', price: 26000, isBillable: true },
  { id: 'srv-9', code: 'SRV-IMG-02', name: 'Ecografía Abdominal Completa', category: 'IMAGENES', price: 29000, isBillable: true },
  { id: 'srv-10', code: 'SRV-IMG-03', name: 'Ecocardiograma Doppler Color', category: 'IMAGENES', price: 42000, isBillable: true },
  { id: 'srv-11', code: 'SRV-PROC-01', name: 'Colocación de Vía Endovenosa / Catéter', category: 'PROCEDIMIENTO', price: 7500, isBillable: true },
  { id: 'srv-12', code: 'SRV-PROC-02', name: 'Curación Simple / Vendaje', category: 'PROCEDIMIENTO', price: 9000, isBillable: true },
  { id: 'srv-13', code: 'SRV-PROC-03', name: 'Sondaje Uretral Evacuador', category: 'PROCEDIMIENTO', price: 18500, isBillable: true },
  { id: 'srv-14', code: 'SRV-PROC-04', name: 'Sesión de Oxigenoterapia (x hora)', category: 'PROCEDIMIENTO', price: 8000, isBillable: true },
  { id: 'srv-15', code: 'SRV-PROC-05', name: 'Nebulización Terapéutica', category: 'PROCEDIMIENTO', price: 6500, isBillable: true },
];


// 4. SESIÓN DE CAJA
export const INITIAL_CASH_SESSIONS: CashRegisterSession[] = [
  {
    id: 'session-1',
    branchId: 'branch-1',
    openedAt: new Date().toISOString(),
    openedBy: 'Superadmin Sistema',
    initialCash: 50000,
    totalIncomeCash: 0,
    totalIncomeDigital: 0,
    totalExpenses: 0,
    isClosed: false,
  },
];

export const INITIAL_CASH_SESSION: CashRegisterSession = INITIAL_CASH_SESSIONS[0];

// 5. CATÁLOGO BASE DE FARMACIA & INSUMOS (VADEMÉCUM INTEGRAL & INSUMOS)
export const INITIAL_PRODUCTS: Product[] = [
  // ========================================================
  // 1. ANALGÉSICOS, AINEs & OPIOIDES
  // ========================================================
  {
    id: 'prod-dipirona',
    code: 'MED-ANA-001',
    commercialName: 'Dipirona 500mg/ml Inyectable',
    activeIngredient: 'Dipirona (Metamizol Sódico)',
    category: 'MEDICAMENTO',
    concentration: '500 mg/ml',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2200,
    salePrice: 5200,
    currentStock: 28,
    minStock: 5,
    currentBatch: 'DIP-2026-X',
    expirationDate: '2027-08-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante A-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-dipirona-500',
  },
  {
    id: 'prod-meloxicam-iny',
    code: 'MED-ANA-002',
    commercialName: 'Meloxicam 0.5% Inyectable',
    activeIngredient: 'Meloxicam',
    category: 'MEDICAMENTO',
    concentration: '0.5% (5 mg/ml)',
    presentation: 'Frasco ampolla 20 ml',
    laboratory: 'Lab Vet',
    costPrice: 6200,
    salePrice: 12500,
    currentStock: 20,
    minStock: 4,
    currentBatch: 'MEL-901',
    expirationDate: '2026-11-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante A-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-meloxicam-05',
  },
  {
    id: 'prod-meloxicam-comp',
    code: 'MED-ANA-003',
    commercialName: 'Meloxicam 2mg Comprimidos',
    activeIngredient: 'Meloxicam',
    category: 'MEDICAMENTO',
    concentration: '2 mg',
    presentation: 'Caja x 10 comprimidos ranurados',
    laboratory: 'Brouwer',
    costPrice: 3800,
    salePrice: 7900,
    currentStock: 35,
    minStock: 6,
    currentBatch: 'MEL-COMP-44',
    expirationDate: '2027-09-15',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante A-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-meloxicam-comp',
  },
  {
    id: 'prod-tramadol-iny',
    code: 'MED-ANA-004',
    commercialName: 'Tramadol 50mg/ml Inyectable',
    activeIngredient: 'Clorhidrato de Tramadol',
    category: 'PSICOTROPICO',
    concentration: '50 mg/ml',
    presentation: 'Ampolla 2 ml',
    laboratory: 'PharmaVet',
    costPrice: 2800,
    salePrice: 5900,
    currentStock: 30,
    minStock: 10,
    currentBatch: 'TRA-441',
    expirationDate: '2027-01-15',
    supplier: 'Droguería Oficial',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-tramadol-inj',
  },
  {
    id: 'prod-tramadol-gotas',
    code: 'MED-ANA-005',
    commercialName: 'Tramadol Gotas Oral 50mg/ml',
    activeIngredient: 'Clorhidrato de Tramadol',
    category: 'PSICOTROPICO',
    concentration: '50 mg/ml (1 gota = 2.5mg)',
    presentation: 'Frasco gotero 10 ml',
    laboratory: 'John Martin',
    costPrice: 4200,
    salePrice: 8900,
    currentStock: 18,
    minStock: 5,
    currentBatch: 'TRA-GOT-89',
    expirationDate: '2027-05-20',
    supplier: 'Droguería Oficial',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-tramadol-gotas',
  },
  {
    id: 'prod-carprofeno',
    code: 'MED-ANA-006',
    commercialName: 'Rimadyl / Carprofeno 100mg',
    activeIngredient: 'Carprofeno',
    category: 'MEDICAMENTO',
    concentration: '100 mg',
    presentation: 'Caja x 14 tabletas masticables',
    laboratory: 'Zoetis',
    costPrice: 9500,
    salePrice: 19800,
    currentStock: 16,
    minStock: 4,
    currentBatch: 'RIM-1022',
    expirationDate: '2027-11-30',
    supplier: 'Droguería Sur',
    location: 'Farmacia Central - Estante A-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-carprofeno-100',
  },
  {
    id: 'prod-dexametasona',
    code: 'MED-ANA-007',
    commercialName: 'Dexametasona 2mg/ml Inyectable',
    activeIngredient: 'Dexametasona 21-Fosfato',
    category: 'MEDICAMENTO',
    concentration: '2 mg/ml',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2400,
    salePrice: 5600,
    currentStock: 25,
    minStock: 5,
    currentBatch: 'DEX-2026-B',
    expirationDate: '2027-10-15',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante A-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-dexametasona-2',
  },
  {
    id: 'prod-prednisolona',
    code: 'MED-ANA-008',
    commercialName: 'Prednisolona 20mg Comprimidos',
    activeIngredient: 'Prednisolona',
    category: 'MEDICAMENTO',
    concentration: '20 mg',
    presentation: 'Blister x 10 comprimidos',
    laboratory: 'Brouwer',
    costPrice: 2100,
    salePrice: 4800,
    currentStock: 40,
    minStock: 6,
    currentBatch: 'PRED-330',
    expirationDate: '2027-12-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante A-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-prednisolona-20',
  },

  // ========================================================
  // 2. GASTROPROTECTORES, ANTIEMÉTICOS & PROCINÉTICOS
  // ========================================================
  {
    id: 'prod-metoclopramida-10',
    code: 'MED-GAS-001',
    commercialName: 'Metoclopramida 10mg/ml Inyectable',
    activeIngredient: 'Metoclopramida Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '10 mg/ml',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2100,
    salePrice: 4900,
    currentStock: 30,
    minStock: 6,
    currentBatch: 'MET-10-2026',
    expirationDate: '2027-08-20',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante B-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-metoclopramida-10',
  },
  {
    id: 'prod-metoclopramida-5',
    code: 'MED-GAS-002',
    commercialName: 'Metoclopramida 5mg/ml Gotas/Inyectable',
    activeIngredient: 'Metoclopramida Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '5 mg/ml',
    presentation: 'Frasco ampolla 20 ml / gotero',
    laboratory: 'Lab Richmond',
    costPrice: 1900,
    salePrice: 4400,
    currentStock: 22,
    minStock: 4,
    currentBatch: 'MET-5-2026',
    expirationDate: '2027-07-15',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante B-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-metoclopramida-5',
  },
  {
    id: 'prod-maropitant',
    code: 'MED-GAS-003',
    commercialName: 'Cerenia / Maropitant 10mg/ml Inyectable',
    activeIngredient: 'Maropitant Citrato',
    category: 'MEDICAMENTO',
    concentration: '10 mg/ml',
    presentation: 'Frasco 20 ml',
    laboratory: 'Zoetis',
    costPrice: 8500,
    salePrice: 16500,
    currentStock: 18,
    minStock: 3,
    currentBatch: 'CER-2026-A',
    expirationDate: '2027-12-31',
    supplier: 'Droguería Sur',
    location: 'Heladera #1 - Medicamentos Fríos',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-maropitant-cerenia',
  },
  {
    id: 'prod-ondansetron',
    code: 'MED-GAS-004',
    commercialName: 'Ondansetrón 2mg/ml Inyectable',
    activeIngredient: 'Ondansetrón Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '2 mg/ml',
    presentation: 'Ampolla 4 ml',
    laboratory: 'Droguería Sur',
    costPrice: 3200,
    salePrice: 7200,
    currentStock: 24,
    minStock: 5,
    currentBatch: 'OND-2026-X',
    expirationDate: '2027-09-30',
    supplier: 'Droguería Sur',
    location: 'Farmacia Central - Estante B-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-ondansetron-2',
  },
  {
    id: 'prod-ranitidina',
    code: 'MED-GAS-005',
    commercialName: 'Ranitidina 25mg/ml Inyectable',
    activeIngredient: 'Ranitidina Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '25 mg/ml',
    presentation: 'Ampolla 5 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2000,
    salePrice: 4600,
    currentStock: 25,
    minStock: 6,
    currentBatch: 'RAN-2026-A',
    expirationDate: '2027-06-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante B-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-ranitidina-25',
  },
  {
    id: 'prod-omeprazol-ev',
    code: 'MED-GAS-006',
    commercialName: 'Omeprazol 40mg Liofilizado EV',
    activeIngredient: 'Omeprazol Sódico',
    category: 'MEDICAMENTO',
    concentration: '40 mg liofilizado',
    presentation: 'Frasco ampolla con solvente',
    laboratory: 'Droguería Central',
    costPrice: 4500,
    salePrice: 9800,
    currentStock: 18,
    minStock: 4,
    currentBatch: 'OME-EV-91',
    expirationDate: '2027-04-30',
    supplier: 'Droguería Central',
    location: 'Farmacia Central - Estante B-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-omeprazol-40-ev',
  },
  {
    id: 'prod-sucralfato',
    code: 'MED-GAS-007',
    commercialName: 'Sucralfato Suspensión 1g/5ml',
    activeIngredient: 'Sucralfato',
    category: 'MEDICAMENTO',
    concentration: '1 g / 5 ml',
    presentation: 'Frasco 100 ml',
    laboratory: 'Lab Farma',
    costPrice: 3400,
    salePrice: 7500,
    currentStock: 20,
    minStock: 5,
    currentBatch: 'SUC-100-26',
    expirationDate: '2027-08-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante B-2',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-sucralfato-susp',
  },

  // ========================================================
  // 3. ANTIBIÓTICOS & ANTIMICROBIANOS
  // ========================================================
  {
    id: 'prod-amoxiclav-comp',
    code: 'MED-ATB-001',
    commercialName: 'Amoxicilina + Ácido Clavulánico 500mg',
    activeIngredient: 'Amoxicilina Trihidrato / Clavulanato Potásico',
    category: 'MEDICAMENTO',
    concentration: '500 mg',
    presentation: 'Caja x 10 comprimidos ranurados',
    laboratory: 'Droguería Central',
    costPrice: 4500,
    salePrice: 9000,
    currentStock: 35,
    minStock: 8,
    currentBatch: 'L-2489',
    expirationDate: '2027-06-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-amoxiclav-comp',
  },
  {
    id: 'prod-amoxiclav-inj',
    code: 'MED-ATB-002',
    commercialName: 'Amoxicilina + Clavulánico Inyectable 140/35mg',
    activeIngredient: 'Amoxicilina / Clavulanato',
    category: 'MEDICAMENTO',
    concentration: '175 mg/ml',
    presentation: 'Frasco ampolla 40 ml',
    laboratory: 'Zoetis',
    costPrice: 7800,
    salePrice: 15500,
    currentStock: 16,
    minStock: 4,
    currentBatch: 'SYN-2026-X',
    expirationDate: '2027-10-31',
    supplier: 'Droguería Sur',
    location: 'Farmacia Central - Estante C-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-amoxiclav-inj',
  },
  {
    id: 'prod-cefalexina',
    code: 'MED-ATB-003',
    commercialName: 'Cefalexina 500mg Comprimidos',
    activeIngredient: 'Cefalexina Monohidrato',
    category: 'MEDICAMENTO',
    concentration: '500 mg',
    presentation: 'Caja x 10 comprimidos',
    laboratory: 'Brouwer',
    costPrice: 3200,
    salePrice: 6800,
    currentStock: 45,
    minStock: 10,
    currentBatch: 'CEF-500-88',
    expirationDate: '2027-11-15',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-cefalexina-500',
  },
  {
    id: 'prod-enrofloxacina-5',
    code: 'MED-ATB-004',
    commercialName: 'Enrofloxacina 5% Inyectable',
    activeIngredient: 'Enrofloxacina',
    category: 'MEDICAMENTO',
    concentration: '50 mg/ml (5%)',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Bayer / Elanco',
    costPrice: 3900,
    salePrice: 8400,
    currentStock: 25,
    minStock: 5,
    currentBatch: 'BAY-5-2026',
    expirationDate: '2027-09-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-enrofloxacina-5',
  },
  {
    id: 'prod-enrofloxacina-10',
    code: 'MED-ATB-005',
    commercialName: 'Enrofloxacina 10% Inyectable',
    activeIngredient: 'Enrofloxacina',
    category: 'MEDICAMENTO',
    concentration: '100 mg/ml (10%)',
    presentation: 'Frasco ampolla 100 ml',
    laboratory: 'Richmond Vet',
    costPrice: 5600,
    salePrice: 12200,
    currentStock: 18,
    minStock: 4,
    currentBatch: 'ENRO-10-X',
    expirationDate: '2027-12-15',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-enrofloxacina-10',
  },
  {
    id: 'prod-metronidazol-ev',
    code: 'MED-ATB-006',
    commercialName: 'Metronidazol 500mg/100ml Infusión EV',
    activeIngredient: 'Metronidazol',
    category: 'MEDICAMENTO',
    concentration: '5 mg/ml (500mg/100ml)',
    presentation: 'Sachet para infusión 100 ml',
    laboratory: 'Baxter',
    costPrice: 2600,
    salePrice: 6200,
    currentStock: 26,
    minStock: 6,
    currentBatch: 'METRO-EV-31',
    expirationDate: '2027-05-31',
    supplier: 'Insumos Médicos',
    location: 'Farmacia Central - Estante C-3',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-metronidazol-ev',
  },
  {
    id: 'prod-gentamicina',
    code: 'MED-ATB-007',
    commercialName: 'Gentamicina 4% Inyectable',
    activeIngredient: 'Sulfato de Gentamicina',
    category: 'MEDICAMENTO',
    concentration: '40 mg/ml (4%)',
    presentation: 'Frasco ampolla 20 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2800,
    salePrice: 6100,
    currentStock: 20,
    minStock: 4,
    currentBatch: 'GEN-4-2026',
    expirationDate: '2027-08-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-3',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-gentamicina-4',
  },
  {
    id: 'prod-ceftriaxona',
    code: 'MED-ATB-008',
    commercialName: 'Ceftriaxona 1g Polvo + Solvente EV/IM',
    activeIngredient: 'Ceftriaxona Sódica',
    category: 'MEDICAMENTO',
    concentration: '1000 mg',
    presentation: 'Frasco ampolla + ampolla diluyente 10ml',
    laboratory: 'Droguería Central',
    costPrice: 4200,
    salePrice: 9500,
    currentStock: 20,
    minStock: 4,
    currentBatch: 'CEF-1G-2026',
    expirationDate: '2027-11-30',
    supplier: 'Droguería Central',
    location: 'Farmacia Central - Estante C-3',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-ceftriaxona-1g',
  },
  {
    id: 'prod-doxiciclina',
    code: 'MED-ATB-009',
    commercialName: 'Doxiciclina 100mg Comprimidos',
    activeIngredient: 'Hiclato de Doxiciclina',
    category: 'MEDICAMENTO',
    concentration: '100 mg',
    presentation: 'Caja x 10 comprimidos',
    laboratory: 'Brouwer',
    costPrice: 3800,
    salePrice: 8200,
    currentStock: 30,
    minStock: 6,
    currentBatch: 'DOX-100-26',
    expirationDate: '2027-10-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Estante C-3',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-doxiciclina-100',
  },

  // ========================================================
  // 4. CARDIORRESPIRATORIOS & URGENCIAS
  // ========================================================
  {
    id: 'prod-furosemida',
    code: 'MED-URG-001',
    commercialName: 'Furosemida 5% Inyectable (Lasix)',
    activeIngredient: 'Furosemida',
    category: 'MEDICAMENTO',
    concentration: '50 mg/ml (5%)',
    presentation: 'Frasco ampolla 20 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2900,
    salePrice: 6500,
    currentStock: 26,
    minStock: 5,
    currentBatch: 'FUR-5-2026',
    expirationDate: '2027-09-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Carro de Paro / Shock Room',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-furosemida-5',
  },
  {
    id: 'prod-adrenalina',
    code: 'MED-URG-002',
    commercialName: 'Adrenalina / Epinefrina 1mg/ml (1:1000)',
    activeIngredient: 'Epinefrina Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '1 mg/ml',
    presentation: 'Ampolla 1 ml',
    laboratory: 'Droguería Sur',
    costPrice: 1800,
    salePrice: 4200,
    currentStock: 35,
    minStock: 10,
    currentBatch: 'ADR-1-2026',
    expirationDate: '2027-12-31',
    supplier: 'Droguería Sur',
    location: 'Carro de Paro / Shock Room',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-adrenalina-1',
  },
  {
    id: 'prod-atropina',
    code: 'MED-URG-003',
    commercialName: 'Atropina Sulfato 1mg/ml Inyectable',
    activeIngredient: 'Sulfato de Atropina',
    category: 'MEDICAMENTO',
    concentration: '1 mg/ml',
    presentation: 'Ampolla 1 ml',
    laboratory: 'Richmond Vet',
    costPrice: 1500,
    salePrice: 3800,
    currentStock: 35,
    minStock: 10,
    currentBatch: 'ATR-1-2026',
    expirationDate: '2027-12-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Carro de Paro / Shock Room',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-atropina-1',
  },
  {
    id: 'prod-lidocaina',
    code: 'MED-URG-004',
    commercialName: 'Lidocaína 2% sin epinefrina',
    activeIngredient: 'Lidocaína Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '20 mg/ml (2%)',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Richmond Vet',
    costPrice: 2200,
    salePrice: 5100,
    currentStock: 25,
    minStock: 6,
    currentBatch: 'LID-2-2026',
    expirationDate: '2027-08-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Carro de Paro / Quirófano',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-lidocaina-2',
  },
  {
    id: 'prod-pimobendan',
    code: 'MED-URG-005',
    commercialName: 'Pimobendan 5mg (Vetmedin)',
    activeIngredient: 'Pimobendan',
    category: 'MEDICAMENTO',
    concentration: '5 mg',
    presentation: 'Caja x 30 comprimidos masticables',
    laboratory: 'Boehringer Ingelheim',
    costPrice: 18500,
    salePrice: 36000,
    currentStock: 12,
    minStock: 3,
    currentBatch: 'PIM-5-88',
    expirationDate: '2027-11-30',
    supplier: 'Droguería Sur',
    location: 'Farmacia Central - Estante D-1',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-pimobendan-5',
  },

  // ========================================================
  // 5. ANESTÉSICOS, SEDANTES & PREMEDICACIÓN
  // ========================================================
  {
    id: 'prod-propofol',
    code: 'MED-ANE-001',
    commercialName: 'Propofol 1% Inyectable (10mg/ml)',
    activeIngredient: 'Propofol',
    category: 'PSICOTROPICO',
    concentration: '10 mg/ml (1%)',
    presentation: 'Ampolla 20 ml',
    laboratory: 'Droguería Sur',
    costPrice: 6500,
    salePrice: 13900,
    currentStock: 20,
    minStock: 5,
    currentBatch: 'PROP-1-2026',
    expirationDate: '2027-04-30',
    supplier: 'Droguería Sur',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-propofol-1',
  },
  {
    id: 'prod-ketamina',
    code: 'MED-ANE-002',
    commercialName: 'Ketamina 10% Inyectable (100mg/ml)',
    activeIngredient: 'Ketamina Clorhidrato',
    category: 'ESTUPEFACIENTE',
    concentration: '100 mg/ml (10%)',
    presentation: 'Frasco ampolla 50 ml',
    laboratory: 'Holliday-Scott',
    costPrice: 8900,
    salePrice: 18500,
    currentStock: 16,
    minStock: 4,
    currentBatch: 'KET-100-26',
    expirationDate: '2027-10-31',
    supplier: 'Droguería Oficial',
    location: 'Caja Fuerte - Controlados Oficiales',
    isNarcotic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-ketamina-10',
  },
  {
    id: 'prod-xilacina',
    code: 'MED-ANE-003',
    commercialName: 'Xilacina 2% Inyectable (20mg/ml)',
    activeIngredient: 'Xilacina Clorhidrato',
    category: 'MEDICAMENTO',
    concentration: '20 mg/ml (2%)',
    presentation: 'Frasco ampolla 20 ml',
    laboratory: 'Richmond Vet',
    costPrice: 3800,
    salePrice: 8200,
    currentStock: 20,
    minStock: 4,
    currentBatch: 'XIL-2-2026',
    expirationDate: '2027-07-31',
    supplier: 'Distribuidora Farmavet',
    location: 'Farmacia Central - Anestesia',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-xilacina-2',
  },
  {
    id: 'prod-diazepam',
    code: 'MED-ANE-004',
    commercialName: 'Diazepam 5mg/ml Inyectable',
    activeIngredient: 'Diazepam',
    category: 'PSICOTROPICO',
    concentration: '5 mg/ml',
    presentation: 'Ampolla 2 ml',
    laboratory: 'Droguería Sur',
    costPrice: 2200,
    salePrice: 5300,
    currentStock: 28,
    minStock: 8,
    currentBatch: 'DIAZ-5-26',
    expirationDate: '2027-12-31',
    supplier: 'Droguería Sur',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-diazepam-5',
  },
  {
    id: 'prod-midazolam',
    code: 'MED-ANE-005',
    commercialName: 'Midazolam 5mg/ml Inyectable',
    activeIngredient: 'Midazolam',
    category: 'PSICOTROPICO',
    concentration: '5 mg/ml',
    presentation: 'Ampolla 3 ml (15mg)',
    laboratory: 'Droguería Central',
    costPrice: 3100,
    salePrice: 6900,
    currentStock: 22,
    minStock: 6,
    currentBatch: 'MID-15-26',
    expirationDate: '2027-08-31',
    supplier: 'Droguería Central',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-midazolam-5',
  },
  {
    id: 'prod-acepromacina',
    code: 'MED-ANE-006',
    commercialName: 'Acepromacina 1% Inyectable (Acedan)',
    activeIngredient: 'Maleate de Acepromacina',
    category: 'PSICOTROPICO',
    concentration: '10 mg/ml (1%)',
    presentation: 'Frasco gotero / ampolla 10 ml',
    laboratory: 'Holliday-Scott',
    costPrice: 2900,
    salePrice: 6400,
    currentStock: 18,
    minStock: 4,
    currentBatch: 'ACE-1-2026',
    expirationDate: '2027-09-30',
    supplier: 'Distribuidora Farmavet',
    location: 'Caja Fuerte - Psicotrópicos',
    isPsychotropic: true,
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-acepromacina-1',
  },
  {
    id: 'prod-isoflurano',
    code: 'MED-ANE-007',
    commercialName: 'Isoflurano Líquido para Inhalación 100ml',
    activeIngredient: 'Isoflurano',
    category: 'MEDICAMENTO',
    concentration: '100% v/v',
    presentation: 'Frasco vidrio ámbar 100 ml',
    laboratory: 'Baxter',
    costPrice: 32000,
    salePrice: 68000,
    currentStock: 8,
    minStock: 2,
    currentBatch: 'ISO-100-26',
    expirationDate: '2028-06-30',
    supplier: 'Insumos Médicos',
    location: 'Quirófano - Vaporizador',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-isoflurano-100',
  },

  // ========================================================
  // 6. FLUIDOS & SOLUCIONES ELECTROLÍTICAS
  // ========================================================
  {
    id: 'prod-ringer-lactato',
    code: 'DES-FLU-001',
    commercialName: 'Solución Ringer Lactato 500ml',
    activeIngredient: 'Solución Polielectrolítica de Ringer con Lactato',
    category: 'DESCARTABLE',
    concentration: '500 ml',
    presentation: 'Sachet colapsable 500 ml',
    laboratory: 'Baxter',
    costPrice: 1800,
    salePrice: 3900,
    currentStock: 50,
    minStock: 15,
    currentBatch: 'RN-8802',
    expirationDate: '2028-03-31',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-1',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-ringer-lactato-500',
  },
  {
    id: 'prod-fisiologica',
    code: 'DES-FLU-002',
    commercialName: 'Solución Fisiológica NaCl 0.9% 500ml',
    activeIngredient: 'Cloruro de Sodio 0.9%',
    category: 'DESCARTABLE',
    concentration: '0.9% (500 ml)',
    presentation: 'Sachet colapsable 500 ml',
    laboratory: 'Baxter',
    costPrice: 1700,
    salePrice: 3800,
    currentStock: 55,
    minStock: 15,
    currentBatch: 'FIS-500-26',
    expirationDate: '2028-04-30',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-1',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-fisiologica-500',
  },
  {
    id: 'prod-dextrosa-5',
    code: 'DES-FLU-003',
    commercialName: 'Solución Dextrosa al 5% 500ml',
    activeIngredient: 'Glucosa Anhidra al 5%',
    category: 'DESCARTABLE',
    concentration: '5% (500 ml)',
    presentation: 'Sachet 500 ml',
    laboratory: 'B. Braun',
    costPrice: 1900,
    salePrice: 4100,
    currentStock: 30,
    minStock: 8,
    currentBatch: 'DEX-500-26',
    expirationDate: '2028-02-28',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-2',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-dextrosa-5-500',
  },
  {
    id: 'prod-manitol',
    code: 'MED-FLU-004',
    commercialName: 'Manitol 20% Infusión EV 250ml',
    activeIngredient: 'Manitol',
    category: 'MEDICAMENTO',
    concentration: '20% (250 ml)',
    presentation: 'Frasco infusión 250 ml',
    laboratory: 'B. Braun',
    costPrice: 4800,
    salePrice: 10500,
    currentStock: 14,
    minStock: 3,
    currentBatch: 'MAN-20-26',
    expirationDate: '2027-11-30',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-2',
    requiresPrescription: true,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-manitol-20',
  },

  // ========================================================
  // 7. DESCARTABLES, JERINGAS, AGUJAS & CATÉTERES
  // ========================================================
  {
    id: 'prod-jeringa-1ml',
    code: 'DES-INS-001',
    commercialName: 'Jeringa 1ml Insulina / TBC',
    activeIngredient: 'Polipropileno grado médico estéril',
    category: 'DESCARTABLE',
    concentration: '1 ml graduada 0.01ml',
    presentation: 'Unidad estéril blister individual',
    laboratory: 'Neojet / Nipro',
    costPrice: 120,
    salePrice: 350,
    currentStock: 120,
    minStock: 40,
    currentBatch: 'JER-1-2026',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Descartables - Gaveta 1',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-jeringa-1ml',
  },
  {
    id: 'prod-jeringa-3ml',
    code: 'DES-INS-002',
    commercialName: 'Jeringa 3ml cono luer',
    activeIngredient: 'Polipropileno grado médico',
    category: 'DESCARTABLE',
    concentration: '3 ml',
    presentation: 'Unidad estéril cono luer lock',
    laboratory: 'Neojet / Nipro',
    costPrice: 140,
    salePrice: 400,
    currentStock: 160,
    minStock: 60,
    currentBatch: 'JER-3-2026',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Descartables - Gaveta 2',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-jeringa-3ml',
  },
  {
    id: 'prod-jeringa-5ml',
    code: 'DES-INS-003',
    commercialName: 'Jeringa 5ml cono luer',
    activeIngredient: 'Polipropileno grado médico',
    category: 'DESCARTABLE',
    concentration: '5 ml',
    presentation: 'Unidad estéril blister',
    laboratory: 'Neojet / Nipro',
    costPrice: 170,
    salePrice: 480,
    currentStock: 130,
    minStock: 50,
    currentBatch: 'JER-5-2026',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Descartables - Gaveta 3',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-jeringa-5ml',
  },
  {
    id: 'prod-jeringa-10ml',
    code: 'DES-INS-004',
    commercialName: 'Jeringa 10ml cono luer',
    activeIngredient: 'Polipropileno grado médico',
    category: 'DESCARTABLE',
    concentration: '10 ml',
    presentation: 'Unidad estéril blister',
    laboratory: 'Neojet / Nipro',
    costPrice: 220,
    salePrice: 600,
    currentStock: 90,
    minStock: 30,
    currentBatch: 'JER-10-2026',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Descartables - Gaveta 4',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-jeringa-10ml',
  },
  {
    id: 'prod-jeringa-20ml',
    code: 'DES-INS-005',
    commercialName: 'Jeringa 20ml cono luer',
    activeIngredient: 'Polipropileno grado médico',
    category: 'DESCARTABLE',
    concentration: '20 ml',
    presentation: 'Unidad estéril',
    laboratory: 'Neojet / Nipro',
    costPrice: 350,
    salePrice: 900,
    currentStock: 70,
    minStock: 20,
    currentBatch: 'JER-20-2026',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Descartables - Gaveta 5',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-jeringa-20ml',
  },
  {
    id: 'prod-aguja-25-8',
    code: 'DES-INS-006',
    commercialName: 'Aguja hipodérmica 25/8 (0.8x25mm)',
    activeIngredient: 'Acero inoxidable siliconado',
    category: 'DESCARTABLE',
    concentration: '21G x 1" (0.8 x 25 mm)',
    presentation: 'Unidad estéril cono verde/azul',
    laboratory: 'Neojet / Nipro',
    costPrice: 60,
    salePrice: 200,
    currentStock: 220,
    minStock: 80,
    currentBatch: 'AGU-258-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Agujas - Caja 1',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-aguja-25-8',
  },
  {
    id: 'prod-aguja-21-5',
    code: 'DES-INS-007',
    commercialName: 'Aguja hipodérmica 21/5 (0.8x15mm)',
    activeIngredient: 'Acero inoxidable siliconado',
    category: 'DESCARTABLE',
    concentration: '21G x 5/8" (0.8 x 15 mm)',
    presentation: 'Unidad estéril',
    laboratory: 'Neojet / Nipro',
    costPrice: 60,
    salePrice: 200,
    currentStock: 220,
    minStock: 80,
    currentBatch: 'AGU-215-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Agujas - Caja 2',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-aguja-21-5',
  },
  {
    id: 'prod-aguja-40-8',
    code: 'DES-INS-008',
    commercialName: 'Aguja hipodérmica 40/8 (0.8x40mm)',
    activeIngredient: 'Acero inoxidable para aspiración/IM profunda',
    category: 'DESCARTABLE',
    concentration: '21G x 1 1/2" (0.8 x 40 mm)',
    presentation: 'Unidad estéril cono verde',
    laboratory: 'Neojet / Nipro',
    costPrice: 70,
    salePrice: 220,
    currentStock: 150,
    minStock: 50,
    currentBatch: 'AGU-408-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Sector Agujas - Caja 3',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-aguja-40-8',
  },
  {
    id: 'prod-cateter-24g',
    code: 'DES-INS-009',
    commercialName: 'Catéter IV 24G amarillo (Abocath)',
    activeIngredient: 'Poliuretano / Teflón radiopaco',
    category: 'DESCARTABLE',
    concentration: '24G x 19 mm',
    presentation: 'Unidad estéril con filtro hidrofóbico',
    laboratory: 'Nipro / BD',
    costPrice: 650,
    salePrice: 1800,
    currentStock: 65,
    minStock: 25,
    currentBatch: 'CAT-24G-26',
    expirationDate: '2029-06-30',
    supplier: 'Insumos Médicos',
    location: 'Sector Catéteres - Gaveta Pediátrica',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-cateter-24g',
  },
  {
    id: 'prod-cateter-22g',
    code: 'DES-INS-010',
    commercialName: 'Catéter IV 22G azul (Abocath)',
    activeIngredient: 'Poliuretano / Teflón radiopaco',
    category: 'DESCARTABLE',
    concentration: '22G x 25 mm',
    presentation: 'Unidad estéril',
    laboratory: 'Nipro / BD',
    costPrice: 650,
    salePrice: 1800,
    currentStock: 90,
    minStock: 35,
    currentBatch: 'CAT-22G-26',
    expirationDate: '2029-06-30',
    supplier: 'Insumos Médicos',
    location: 'Sector Catéteres - Gaveta Estándar',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-cateter-22g',
  },
  {
    id: 'prod-cateter-20g',
    code: 'DES-INS-011',
    commercialName: 'Catéter IV 20G rosa (Abocath)',
    activeIngredient: 'Poliuretano radiopaco',
    category: 'DESCARTABLE',
    concentration: '20G x 32 mm',
    presentation: 'Unidad estéril',
    laboratory: 'Nipro / BD',
    costPrice: 680,
    salePrice: 1900,
    currentStock: 55,
    minStock: 20,
    currentBatch: 'CAT-20G-26',
    expirationDate: '2029-06-30',
    supplier: 'Insumos Médicos',
    location: 'Sector Catéteres - Gaveta Grandes/Urgencia',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-cateter-20g',
  },
  {
    id: 'prod-guia-suero',
    code: 'DES-INS-012',
    commercialName: 'Guía de perfusión macrogotero con filtro',
    activeIngredient: 'PVC grado médico atóxico',
    category: 'DESCARTABLE',
    concentration: 'Macrogotero estándar (20 gotas/ml)',
    presentation: 'Unidad estéril con regulador roller',
    laboratory: 'B. Braun / Nipro',
    costPrice: 950,
    salePrice: 2600,
    currentStock: 80,
    minStock: 30,
    currentBatch: 'GUI-MAC-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-3',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-guia-suero',
  },
  {
    id: 'prod-llave-3-vias',
    code: 'DES-INS-013',
    commercialName: 'Llave de 3 vías con prolongador',
    activeIngredient: 'Policarbonato liporesistente',
    category: 'DESCARTABLE',
    concentration: '3 vías con tapón luer',
    presentation: 'Unidad estéril',
    laboratory: 'B. Braun',
    costPrice: 550,
    salePrice: 1600,
    currentStock: 70,
    minStock: 25,
    currentBatch: 'LLAV-3V-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Depósito Fluidoterapia - Estante F-3',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-llave-3-vias',
  },
  {
    id: 'prod-gasas-esteriles',
    code: 'INS-QUI-014',
    commercialName: 'Gasas hidrófilas estériles sobre x 10',
    activeIngredient: '100% Algodón puro blanqueado',
    category: 'INSUMO_QUIRURGICO',
    concentration: '10 x 10 cm (Sobre x 10)',
    presentation: 'Sobre estéril papel grado médico',
    laboratory: 'Textil Médica',
    costPrice: 380,
    salePrice: 950,
    currentStock: 100,
    minStock: 30,
    currentBatch: 'GAS-EST-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Quirófano & Curaciones',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-gasas-esteriles',
  },
  {
    id: 'prod-venda-coban',
    code: 'INS-QUI-015',
    commercialName: 'Venda elástica autoadhesiva Coban 5cm',
    activeIngredient: 'Fibras no tejidas elastoméricas',
    category: 'INSUMO_QUIRURGICO',
    concentration: '5 cm x 4.5 m',
    presentation: 'Rollo individual',
    laboratory: '3M / Coban',
    costPrice: 1200,
    salePrice: 2900,
    currentStock: 45,
    minStock: 15,
    currentBatch: 'COB-5CM-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Quirófano & Curaciones',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-venda-coban',
  },
  {
    id: 'prod-cinta-leukoplast',
    code: 'INS-QUI-016',
    commercialName: 'Cinta adhesiva hipoalergénica Leukoplast',
    activeIngredient: 'Seda artificial con adhesivo óxido de zinc',
    category: 'INSUMO_QUIRURGICO',
    concentration: '2.5 cm x 5 m',
    presentation: 'Carretel con funda protectora',
    laboratory: 'BSN Medical',
    costPrice: 1600,
    salePrice: 3600,
    currentStock: 35,
    minStock: 10,
    currentBatch: 'LEUKO-26',
    expirationDate: '2029-12-31',
    supplier: 'Insumos Médicos',
    location: 'Quirófano & Curaciones',
    requiresPrescription: false,
    branchId: 'branch-1',
    vademecumSourceId: 'vad-cinta-leukoplast',
  },
  // 8. BIOLÓGICOS / VACUNAS
  {
    id: 'prod-vacuna-sextuple',
    code: 'VAC-001',
    commercialName: 'Vacuna Séxtuple Canina (DHPPi+L)',
    activeIngredient: 'Biológico Canino Múltiple',
    category: 'VACUNA',
    concentration: 'Monodosis',
    presentation: 'Dosis monodosis liofilizada + diluyente',
    laboratory: 'Zoetis',
    costPrice: 8500,
    salePrice: 18000,
    currentStock: 35,
    minStock: 10,
    currentBatch: 'V6-7781',
    expirationDate: '2026-10-31',
    supplier: 'Distribuidora Biológicos',
    location: 'Heladera #2 - Vacunas',
    requiresPrescription: true,
    branchId: 'branch-1',
  },
  {
    id: 'prod-vacuna-antirrabica',
    code: 'VAC-002',
    commercialName: 'Vacuna Antirrábica Inactivada',
    activeIngredient: 'Virus Rábico Inactivado Cepa Pasteur',
    category: 'VACUNA',
    concentration: '1 ml monodosis',
    presentation: 'Frasco ampolla monodosis',
    laboratory: 'Biogénesis Bagó',
    costPrice: 4200,
    salePrice: 9500,
    currentStock: 40,
    minStock: 10,
    currentBatch: 'RAB-2026-X',
    expirationDate: '2027-06-30',
    supplier: 'Distribuidora Biológicos',
    location: 'Heladera #2 - Vacunas',
    requiresPrescription: true,
    branchId: 'branch-1',
  },
];

// 6. REGLAS REGULATORIAS
export const INITIAL_REGULATORY_RULES: RegulatoryRule[] = [
  {
    id: 'rule-1',
    country: 'Argentina',
    province: 'Neuquén',
    municipality: 'Las Lajas',
    organism: 'COLEGIO_MEDICO_VETERINARIO_NEUQUEN',
    lawTitle: 'Estatuto de Ejercicio Profesional CMVN Neuquén',
    lawNumber: 'Matrícula Provincial 502',
    articleSection: 'Art. 1 al 45',
    description: 'Obligación de matrícula profesional habilitante y dirección técnica.',
    clinicalImpactSummary: 'Firma y sello digital obligatorio en consultas.',
    affectedModule: 'EJERCICIO_PROFESIONAL',
    isMandatory: true,
    effectiveDate: '2020-01-01',
    version: '1.0',
    lastReviewedAt: '2026-01-01',
    reviewedBy: 'Dr. Diego Iván Irusta',
    status: 'VIGENTE',
  },
  {
    id: 'rule-2',
    country: 'Argentina',
    province: 'Nacional',
    municipality: 'General',
    organism: 'SENASA',
    lawTitle: 'Receta Veterinaria Electrónica RVE SENASA',
    lawNumber: 'Res. SENASA 169/2021',
    articleSection: 'Art. 12',
    description: 'Prescripción digital de antimicrobianos y fármacos controlados.',
    clinicalImpactSummary: 'Emisión de duplicados y archivo digital oficial.',
    affectedModule: 'RECETARIO_SENASA',
    isMandatory: true,
    effectiveDate: '2021-06-01',
    version: '2.1',
    lastReviewedAt: '2026-01-01',
    reviewedBy: 'Dr. Diego Iván Irusta',
    status: 'VIGENTE',
  },
  {
    id: 'rule-3',
    country: 'Argentina',
    province: 'Neuquén',
    municipality: 'Las Lajas',
    organism: 'SECRETARIA_AMBIENTE_NEUQUEN',
    lawTitle: 'Residuos Patológicos Ley Provincial 1.875 y Ley Nacional 24.051',
    lawNumber: 'Ley 24.051 / Ley 1.875',
    articleSection: 'Capítulo IV',
    description: 'Segregación de residuos biopatogénicos en bolsa roja.',
    clinicalImpactSummary: 'Manifiesto de retiro y certificado de disposición final.',
    affectedModule: 'RESIDUOS_PATOLOGICOS',
    isMandatory: true,
    effectiveDate: '2018-01-01',
    version: '1.0',
    lastReviewedAt: '2026-01-01',
    reviewedBy: 'Dr. Diego Iván Irusta',
    status: 'VIGENTE',
  },
  {
    id: 'rule-4',
    country: 'Argentina',
    province: 'Nacional',
    municipality: 'General',
    organism: 'MINISTERIO_SALUD',
    lawTitle: 'Ley 25.326 de Protección de Datos Personales',
    lawNumber: 'Ley 25.326',
    articleSection: 'Art. 5 y 9',
    description: 'Protección y enmascaramiento de datos personales de tutores.',
    clinicalImpactSummary: 'Control de acceso por roles RBAC.',
    affectedModule: 'PROTECCION_DATOS',
    isMandatory: true,
    effectiveDate: '2000-10-30',
    version: '1.0',
    lastReviewedAt: '2026-01-01',
    reviewedBy: 'Dr. Diego Iván Irusta',
    status: 'VIGENTE',
  },
];

// 7. CATÁLOGO DE CONTROLADOS
export const INITIAL_CONTROLLED_DRUGS: ControlledDrugItem[] = [
  {
    id: 'ctrl-1',
    commercialName: 'Tramadol 50mg/ml Inyectable',
    activeIngredient: 'Clorhidrato de Tramadol',
    concentration: '50mg/ml',
    presentation: 'Ampolla 2ml',
    laboratory: 'PharmaVet',
    senasaCategory: 'CAT_I_OFICIAL_ARCHIVADA',
    currentStock: 30,
    unit: 'Ampolla',
    minStock: 10,
    lawClassification: 'LEY_19303_PSICOTROPICOS',
  },
  {
    id: 'ctrl-2',
    commercialName: 'Ketamina 10% 50ml',
    activeIngredient: 'Clorhidrato de Ketamina',
    concentration: '100mg/ml',
    presentation: 'Frasco 50ml',
    laboratory: 'Lab Vet',
    senasaCategory: 'CAT_I_OFICIAL_ARCHIVADA',
    currentStock: 10,
    unit: 'Frasco',
    minStock: 2,
    lawClassification: 'KETAMINA_RESOLUCION_SENASA',
  },
];
