import {
  Branch,
  User,
  Owner,
  Patient,
  VitalSigns,
  Consultation,
  Hospitalization,
  SurgeryRecord,
  LaboratoryOrder,
  ImagingStudy,
  VaccinationRecord,
  Product,
  Appointment,
  TriageEntry,
  Invoice,
  Estimate,
  CashRegisterSession,
  ClinicalDocument,
  AuditLog,
  PatientProblem,
} from './types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-1',
    name: 'Hospital Central 24 Horas',
    code: 'HC-01',
    address: 'Av. Corrientes 4550, CABA',
    phone: '+54 11 4862-9900',
    whatsapp: '+54 9 11 3822-9011',
    email: 'contacto@vetsystem.com.ar',
    cuit: '30-71458920-4',
    taxCondition: 'IVA Responsable Inscripto',
  },
  {
    id: 'branch-2',
    name: 'Clínica & Consultorios Norte',
    code: 'CN-02',
    address: 'Av. Maipú 2140, Olivos, Buenos Aires',
    phone: '+54 11 4791-3320',
    whatsapp: '+54 9 11 4455-8812',
    email: 'norte@vetsystem.com.ar',
    cuit: '30-71458920-4',
    taxCondition: 'IVA Responsable Inscripto',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Dr. Martín López',
    email: 'mlopez@vetsystem.com.ar',
    role: 'VETERINARIO',
    licenseNumber: 'MP 8412 - Cirugía & UCI',
    branchId: 'branch-1',
  },
  {
    id: 'user-2',
    name: 'Dra. Carolina Silva',
    email: 'csilva@vetsystem.com.ar',
    role: 'VETERINARIO',
    licenseNumber: 'MP 9520 - Clínica Médica & Felinos',
    branchId: 'branch-1',
  },
  {
    id: 'user-3',
    name: 'Lic. Gonzalo Rossi',
    email: 'grossi@vetsystem.com.ar',
    role: 'ENFERMERIA',
    branchId: 'branch-1',
  },
  {
    id: 'user-4',
    name: 'Romina Juárez',
    email: 'rjuarez@vetsystem.com.ar',
    role: 'RECEPCION',
    branchId: 'branch-1',
  },
  {
    id: 'user-5',
    name: 'Matías Beltrán',
    email: 'mbeltran@vetsystem.com.ar',
    role: 'CAJA',
    branchId: 'branch-1',
  },
  {
    id: 'user-6',
    name: 'Superadmin Sistema',
    email: 'admin@vetsystem.com.ar',
    role: 'SUPERADMIN',
    branchId: 'branch-1',
  },
];

export const INITIAL_OWNERS: Owner[] = [
  {
    id: 'owner-1',
    firstName: 'Juan Pablo',
    lastName: 'Pérez Rossi',
    dni: '32.458.912',
    cuit: '20-32458912-8',
    phone: '+54 9 11 5482-1190',
    whatsapp: '+54 9 11 5482-1190',
    email: 'juanp.perez@gmail.com',
    address: 'Av. Libertador 2450, Piso 4B',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1425',
    notes: 'Tutor muy atento y puntual con los controles. Tiene 2 mascotas.',
    balance: 0,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'owner-2',
    firstName: 'María Eugenia',
    lastName: 'González',
    dni: '28.914.502',
    phone: '+54 9 11 6720-4411',
    whatsapp: '+54 9 11 6720-4411',
    email: 'mariaeugenia.g@hotmail.com',
    address: 'Calle Mendoza 1420',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1428',
    notes: 'Tutora de Luna. Prefiere recordatorios por WhatsApp.',
    balance: 0,
    createdAt: '2025-02-10T14:30:00Z',
  },
  {
    id: 'owner-3',
    firstName: 'Esteban',
    lastName: 'Ríos',
    dni: '35.120.489',
    cuit: '20-35120489-3',
    phone: '+54 9 11 4190-8822',
    whatsapp: '+54 9 11 4190-8822',
    email: 'erios_ar@yahoo.com.ar',
    address: 'Av. Cabildo 3100',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1429',
    notes: 'Tutor de Rocky (Bulldog Francés). Solicita siempre Factura A.',
    balance: 15400,
    createdAt: '2025-03-01T09:15:00Z',
  },
  {
    id: 'owner-4',
    firstName: 'Lucía',
    lastName: 'Fernández',
    dni: '39.840.112',
    phone: '+54 9 11 3322-7788',
    whatsapp: '+54 9 11 3322-7788',
    email: 'lucia.fernandez98@gmail.com',
    address: 'Gorriti 4820',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1414',
    notes: 'Tutora de Milo. Notificar inmediatamente ante cualquier cambio en internación.',
    balance: 0,
    createdAt: '2025-04-12T11:20:00Z',
  },
  {
    id: 'owner-5',
    firstName: 'Alejandro',
    lastName: 'Morales',
    dni: '25.680.993',
    cuit: '20-25680993-8',
    phone: '+54 9 11 8844-3311',
    whatsapp: '+54 9 11 8844-3311',
    email: 'amorales@agroempresas.com.ar',
    address: 'Av. Santa Fe 1820',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1123',
    notes: 'Tutor de Nina (Ovejero Alemán). Excelente predisposición para rehabilitación.',
    balance: 0,
    createdAt: '2025-05-02T16:00:00Z',
  },
  {
    id: 'owner-6',
    firstName: 'Florencia',
    lastName: 'Vázquez',
    dni: '41.205.881',
    phone: '+54 9 11 9911-2244',
    whatsapp: '+54 9 11 9911-2244',
    email: 'flor.vazquez@gmail.com',
    address: 'Calle Juramento 2900',
    city: 'CABA',
    province: 'Buenos Aires',
    postalCode: 'C1428',
    notes: 'Tutora de Simón y Cleo.',
    balance: 0,
    createdAt: '2025-06-18T12:00:00Z',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    clinicalRecordNumber: 'HC-10042',
    name: 'Toby',
    species: 'CANINO',
    breed: 'Golden Retriever',
    sex: 'MACHO',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2020-04-10',
    calculatedAge: '4 años, 10 meses',
    weight: 32.5,
    color: 'Dorado / Crema',
    microchip: '981098123456789',
    photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=300',
    ownerId: 'owner-1',
    primaryVetId: 'user-1',
    status: 'INTERNADO',
    alerts: [
      {
        type: 'ALERGIA',
        description: 'Alérgico a Dipirona / AINEs inyectables (provoca hipotensión reactiva). Usar Tramadol.',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-01-15T10:30:00Z',
  },
  {
    id: 'pat-2',
    clinicalRecordNumber: 'HC-10043',
    name: 'Luna',
    species: 'FELINO',
    breed: 'Siamés Tradicional',
    sex: 'HEMBRA',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2017-08-15',
    calculatedAge: '7 años, 6 meses',
    weight: 4.2,
    color: 'Seal Point',
    microchip: '981098123456790',
    photoUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300',
    ownerId: 'owner-2',
    primaryVetId: 'user-2',
    status: 'ACTIVO',
    alerts: [
      {
        type: 'RENAL',
        description: 'Enfermedad Renal Crónica IRIS Estadio 2. Monitorear Presión Arterial y SDMA.',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-02-10T14:35:00Z',
  },
  {
    id: 'pat-3',
    clinicalRecordNumber: 'HC-10044',
    name: 'Rocky',
    species: 'CANINO',
    breed: 'Bulldog Francés',
    sex: 'MACHO',
    reproductiveStatus: 'ENTERO',
    birthDate: '2022-03-20',
    calculatedAge: '2 años, 11 meses',
    weight: 12.8,
    color: 'Atigrado / Brindle',
    microchip: '981098123456791',
    photoUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300',
    ownerId: 'owner-3',
    primaryVetId: 'user-1',
    status: 'ACTIVO',
    alerts: [
      {
        type: 'ALERGIA',
        description: 'Alergia severa a Penicilinas y Cefalosporinas de 1ra generación.',
      },
      {
        type: 'RIESGO_ANESTESICO',
        description: 'Síndrome Braquicefálico (BOAS). Monitoreo estricto de vía aérea y preoxigenación.',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-03-01T09:20:00Z',
  },
  {
    id: 'pat-4',
    clinicalRecordNumber: 'HC-10045',
    name: 'Milo',
    species: 'FELINO',
    breed: 'Europeo Común / Mestizo',
    sex: 'MACHO',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2021-11-05',
    calculatedAge: '3 años, 3 meses',
    weight: 5.1,
    color: 'Naranja Atigrado',
    microchip: '981098123456792',
    photoUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=300',
    ownerId: 'owner-4',
    primaryVetId: 'user-2',
    status: 'INTERNADO',
    alerts: [
      {
        type: 'MEDICACION_CRONICA',
        description: 'Sonda uretral colocada. Monitorear diuresis horaria (> 2 ml/kg/h).',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-04-12T11:30:00Z',
  },
  {
    id: 'pat-5',
    clinicalRecordNumber: 'HC-10046',
    name: 'Nina',
    species: 'CANINO',
    breed: 'Ovejero Alemán',
    sex: 'HEMBRA',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2019-06-12',
    calculatedAge: '5 años, 8 meses',
    weight: 28.4,
    color: 'Negro y Fuego',
    microchip: '981098123456793',
    photoUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5455?w=300',
    ownerId: 'owner-5',
    primaryVetId: 'user-1',
    status: 'ACTIVO',
    alerts: [
      {
        type: 'MEDICACION_CRONICA',
        description: 'Posquirúrgico TPLO miembro posterior izquierdo. Reposo y collar isabelino.',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-05-02T16:10:00Z',
  },
  {
    id: 'pat-6',
    clinicalRecordNumber: 'HC-10047',
    name: 'Simón',
    species: 'CANINO',
    breed: 'Caniche Toy',
    sex: 'MACHO',
    reproductiveStatus: 'CASTRADO',
    birthDate: '2014-09-02',
    calculatedAge: '10 años, 5 meses',
    weight: 4.8,
    color: 'Blanco',
    microchip: '981098123456794',
    photoUrl: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=300',
    ownerId: 'owner-6',
    primaryVetId: 'user-2',
    status: 'ACTIVO',
    alerts: [
      {
        type: 'CARDIOPATIA',
        description: 'Insuficiencia Mitral ACVIM Estadio C. En tratamiento con Pimobendan y Furosemida.',
      },
    ],
    branchId: 'branch-1',
    createdAt: '2025-06-18T12:10:00Z',
  },
  {
    id: 'pat-7',
    clinicalRecordNumber: 'HC-10048',
    name: 'Cleo',
    species: 'EXOTICO',
    breed: 'Conejo Mini Lop',
    sex: 'HEMBRA',
    reproductiveStatus: 'ENTERO',
    birthDate: '2023-01-10',
    calculatedAge: '2 años, 1 mes',
    weight: 1.95,
    color: 'Gris Ceniza',
    microchip: '981098123456795',
    photoUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=300',
    ownerId: 'owner-6',
    primaryVetId: 'user-2',
    status: 'ACTIVO',
    alerts: [],
    branchId: 'branch-1',
    createdAt: '2025-07-05T15:00:00Z',
  },
];

export const INITIAL_VITALS: VitalSigns[] = [
  {
    id: 'vit-1',
    patientId: 'pat-1',
    recordedAt: '2025-02-18T09:00:00Z',
    recordedBy: 'Dr. Martín López',
    weight: 32.5,
    temperature: 39.1,
    heartRate: 118,
    respiratoryRate: 28,
    systolicBP: 115,
    diastolicBP: 72,
    meanBP: 86,
    spo2: 98,
    bloodGlucose: 104,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 2,
    bodyConditionScore: '5/9',
    notes: 'Paciente internado hemodinámicamente estable. Ruidos hidroaéreos disminuidos. Abdomen blando no doloroso.',
  },
  {
    id: 'vit-2',
    patientId: 'pat-1',
    recordedAt: '2025-02-17T20:00:00Z',
    recordedBy: 'Lic. Gonzalo Rossi',
    weight: 32.2,
    temperature: 39.4,
    heartRate: 132,
    respiratoryRate: 34,
    systolicBP: 105,
    diastolicBP: 65,
    meanBP: 78,
    spo2: 97,
    bloodGlucose: 118,
    mucousMembranes: 'CONGESTIVAS',
    capillaryRefillTime: 2.0,
    hydrationStatus: 'DESHIDRATACION_5',
    consciousnessLevel: 'DEPRIMIDO',
    painScale: 4,
    bodyConditionScore: '5/9',
    notes: 'Ingreso a internación por vómitos y dolor epigástrico. Se inicia fluidoterapia.',
  },
  {
    id: 'vit-3',
    patientId: 'pat-2',
    recordedAt: '2025-02-15T11:00:00Z',
    recordedBy: 'Dra. Carolina Silva',
    weight: 4.2,
    temperature: 38.6,
    heartRate: 165,
    respiratoryRate: 26,
    systolicBP: 142,
    diastolicBP: 92,
    meanBP: 108,
    spo2: 99,
    bloodGlucose: 92,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 0,
    bodyConditionScore: '4/9',
    notes: 'Control trimestral de ERC. Normotermia. Presión arterial controlada con Amlodipino.',
  },
  {
    id: 'vit-4',
    patientId: 'pat-3',
    recordedAt: '2025-02-10T16:30:00Z',
    recordedBy: 'Dr. Martín López',
    weight: 12.8,
    temperature: 38.8,
    heartRate: 124,
    respiratoryRate: 32,
    systolicBP: 130,
    diastolicBP: 80,
    meanBP: 96,
    spo2: 96,
    bloodGlucose: 98,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 1,
    bodyConditionScore: '6/9',
    notes: 'Evaluación prequirúrgica para rinoplastia de narinas. Ronquidos inspiratorios leves.',
  },
  {
    id: 'vit-5',
    patientId: 'pat-4',
    recordedAt: '2025-02-18T08:30:00Z',
    recordedBy: 'Lic. Gonzalo Rossi',
    weight: 5.1,
    temperature: 38.3,
    heartRate: 175,
    respiratoryRate: 28,
    systolicBP: 125,
    diastolicBP: 78,
    meanBP: 93,
    spo2: 98,
    bloodGlucose: 110,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 2,
    bodyConditionScore: '5/9',
    notes: 'Sonda urinaria permeable con orina clara. Bolsa colectora 45 ml en 6 horas.',
  },
  {
    id: 'vit-6',
    patientId: 'pat-5',
    recordedAt: '2025-02-14T15:00:00Z',
    recordedBy: 'Dr. Martín López',
    weight: 28.4,
    temperature: 38.5,
    heartRate: 98,
    respiratoryRate: 22,
    systolicBP: 120,
    diastolicBP: 75,
    meanBP: 90,
    spo2: 99,
    bloodGlucose: 96,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 1,
    bodyConditionScore: '5/9',
    notes: 'Control posquirúrgico TPLO (Día 12). Retiro de puntos de sutura. Apoyo parcial de extremidad.',
  },
  {
    id: 'vit-7',
    patientId: 'pat-6',
    recordedAt: '2025-02-12T10:00:00Z',
    recordedBy: 'Dra. Carolina Silva',
    weight: 4.8,
    temperature: 38.4,
    heartRate: 138,
    respiratoryRate: 24,
    systolicBP: 118,
    diastolicBP: 70,
    meanBP: 86,
    spo2: 97,
    bloodGlucose: 90,
    mucousMembranes: 'ROSADAS',
    capillaryRefillTime: 1.5,
    hydrationStatus: 'NORMAL',
    consciousnessLevel: 'ALERTA',
    painScale: 0,
    bodyConditionScore: '5/9',
    notes: 'Soplo holosistólico apical izquierdo Grado IV/VI. Sin estertores pulmonares. FR en reposo 22 rpm.',
  },
];

export const INITIAL_CONSULTATIONS: Consultation[] = [
  {
    id: 'cons-1',
    patientId: 'pat-1',
    vetId: 'user-1',
    vetName: 'Dr. Martín López',
    branchId: 'branch-1',
    dateTime: '2025-02-17T19:30:00Z',
    reason: 'Vómitos agudos recurrentes (4 episodios) y decaimiento marcado',
    anamnesis: 'Tutor refiere que el paciente ingirió restos de asado hace 24 horas. Comenzó con inquietud y vómitos alimentarios que viraron a biliosos.',
    vitalSigns: INITIAL_VITALS[1],
    physicalExam: {
      general: 'Decaído, alerta, postura antiálgica.',
      skinAndCoat: 'Pérdida leve de turgencia cutánea (deshidratación 5%).',
      eyes: 'Conjuntivas normales, reflejo pupilar conservado.',
      ears: 'Conductos auditivos limpios sin secreciones.',
      oralCavity: 'Mucosas congestivas, TLLC 2 seg.',
      lymphNodes: 'Ganglios simétricos no reactivos.',
      cardiovascular: 'Taquicardia sinusal, pulsos periféricos simétricos.',
      respiratory: 'Taquipnea eupneica, campos libres.',
      digestive: 'Dolor y tensión a la palpación epigástrica.',
      urinary: 'Vejiga moderadamente pletórica no dolorosa.',
      reproductive: 'Castrado sin particularidades.',
      musculoskeletal: 'Sin claudicaciones evidentes.',
      neurological: 'Reflejos normales.',
    },
    soap: {
      id: 'soap-1',
      consultationId: 'cons-1',
      patientId: 'pat-1',
      subjective: 'Inquietud, dolor abdominal moderado a la palpación epigástrica.',
      objective: 'FC 132 lpm, FR 34 rpm, Temp 39.4°C, SpO2 97%, PAM 78 mmHg.',
      assessment: 'Gastroenteritis aguda severa con deshidratación 5%. Descartar cuerpo extraño.',
      plan: 'Internación en UCI con fluidoterapia Ringer Lactato a 80 ml/h + Cerenia + Omeprazol.',
      createdAt: '2025-02-17T20:00:00Z',
      vetName: 'Dr. Martín López',
    },
    diagnoses: ['Gastroenteritis aguda severa', 'Deshidratación 5%'],
    differentialDiagnoses: ['Cuerpo extraño gástrico', 'Pancreatitis aguda'],
    treatmentPlan: 'Internación en UCI, fluidoterapia Ringer Lactato a 80 ml/h, analgesia con Tramadol.',
    prescriptions: [
      { id: 'rx-1', medicationName: 'Cerenia (Maropitant 10mg/ml)', presentation: 'Inyectable SC', dose: '1 mg/kg (3.2 ml)', route: 'SC', frequency: 'Cada 24 horas', duration: '3 días', instructions: 'Aplicar vía subcutánea lenta.' },
      { id: 'rx-2', medicationName: 'Omeprazol 40mg', presentation: 'Inyectable IV', dose: '1 mg/kg (32 mg)', route: 'IV', frequency: 'Cada 24 horas', duration: '5 días', instructions: 'Diluir en 20ml SF y pasar lento.' },
      { id: 'rx-3', medicationName: 'Tramadol Clorhidrato 50mg/ml', presentation: 'Inyectable SC', dose: '2 mg/kg (1.3 ml)', route: 'SC', frequency: 'Cada 8 horas', duration: '2 días', instructions: 'Analgesia visceral de rescate.' },
    ],
    orderedStudies: ['Hemograma Completo', 'Bioquímica Urgente', 'Radiografía Digital de Abdomen'],
    requiresHospitalization: true,
    status: 'FINALIZADA',
  },
  {
    id: 'cons-2',
    patientId: 'pat-2',
    vetId: 'user-2',
    vetName: 'Dra. Carolina Silva',
    branchId: 'branch-1',
    dateTime: '2025-02-15T10:30:00Z',
    reason: 'Control periódico de Enfermedad Renal Crónica (ERC)',
    anamnesis: 'Tutora refiere que Luna mantiene buen apetito con la comida renal húmeda. Micción regular sin vómitos.',
    vitalSigns: INITIAL_VITALS[2],
    physicalExam: {
      general: 'Estado general óptimo, reactiva y dócil.',
      skinAndCoat: 'Piel elástica, pelaje limpio.',
      eyes: 'Fondo de ojo sin hemorragias.',
      ears: 'Conductos limpios.',
      oralCavity: 'Gingivitis marginal leve.',
      lymphNodes: 'Normales.',
      cardiovascular: 'R1 y R2 normofonéticos.',
      respiratory: 'Campos pulmonares limpios.',
      digestive: 'Riñón izquierdo ligeramente pequeño.',
      urinary: 'Micción conservada.',
      reproductive: 'Esterilizada.',
      musculoskeletal: 'Sin dolor articular.',
      neurological: 'Normal.',
    },
    soap: {
      id: 'soap-2',
      consultationId: 'cons-2',
      patientId: 'pat-2',
      subjective: 'Paciente tranquila, apetito conservado.',
      objective: 'Peso 4.2 kg, FC 165 lpm, PAM 108 mmHg, Temp 38.6°C.',
      assessment: 'ERC IRIS Estadio 2 compensada con normotensión farmacológica.',
      plan: 'Mantener Amlodipino 0.625 mg/día y Benazepril 2.5 mg/día. Próximo control en 90 días.',
      createdAt: '2025-02-15T11:00:00Z',
      vetName: 'Dra. Carolina Silva',
    },
    diagnoses: ['Enfermedad Renal Crónica IRIS Estadio 2'],
    differentialDiagnoses: [],
    treatmentPlan: 'Continuar con dieta renal estricta y antihipertensivos.',
    prescriptions: [
      { id: 'rx-4', medicationName: 'Amlodipino 5mg', presentation: 'Comprimidos', dose: '0.625 mg (1/8 comp)', route: 'ORAL', frequency: 'Cada 24 horas', duration: 'Crónico', instructions: 'Dar por la mañana con comida.' },
      { id: 'rx-5', medicationName: 'Benazepril 5mg (Fortekor)', presentation: 'Comprimidos', dose: '2.5 mg (1/2 comp)', route: 'ORAL', frequency: 'Cada 24 horas', duration: 'Crónico', instructions: 'Dar por la noche.' },
    ],
    orderedStudies: ['Panel Renal Felino + SDMA'],
    requiresHospitalization: false,
    status: 'FINALIZADA',
  },
];

export const INITIAL_HOSPITALIZATIONS: Hospitalization[] = [
  {
    id: 'hosp-1',
    patientId: 'pat-1',
    vetInChargeId: 'user-1',
    vetInChargeName: 'Dr. Martín López',
    sector: 'UCI',
    kennelNumber: 'UCI-01',
    admittedAt: '2025-02-17T20:00:00Z',
    primaryDiagnosis: 'Gastroenteritis aguda severa con deshidratación',
    priority: 'PRIORITARIO',
    fluidTherapy: {
      isActive: true,
      solutionType: 'Ringer Lactato Baxter',
      volumeTotalMl: 2000,
      rateMlPerHour: 80,
      dropsPerMinute: 27,
      infusionRoute: 'IV',
      startedAt: '2025-02-17T20:30:00Z',
      additives: 'KCl 20 mEq/L',
      prescribedBy: 'Dr. Martín López',
    },
    feeding: {
      dietType: 'NPO_AYUNO',
      foodBrand: 'Hill\'s i/d Digestive Care',
      amountGramsOrMl: 100,
      frequency: 'Cada 6 horas tras 12h de ayuno',
      tolerance: 'EXCELENTE',
    },
    eliminations: [
      { id: 'el-1', timestamp: '2025-02-18T04:00:00Z', type: 'MICCION', amount: 'MODERADA', aspect: 'Orina clara normal', registeredBy: 'Lic. Gonzalo Rossi' },
      { id: 'el-2', timestamp: '2025-02-18T08:00:00Z', type: 'MICCION', amount: 'ABUNDANTE', aspect: 'Orina clara', registeredBy: 'Lic. Gonzalo Rossi' },
    ],
    medications: [
      { id: 'med-1', hospitalizationId: 'hosp-1', patientId: 'pat-1', drugName: 'Cerenia (Maropitant 10mg/ml)', dose: '32 mg (3.2 ml SC)', route: 'SC', frequencyHours: 24, scheduledTime: '08:00', status: 'REALIZADA', administeredAt: '2025-02-18T08:00:00Z', administeredBy: 'Lic. Gonzalo Rossi' },
      { id: 'med-2', hospitalizationId: 'hosp-1', patientId: 'pat-1', drugName: 'Omeprazol IV', dose: '32 mg IV', route: 'IV', frequencyHours: 24, scheduledTime: '08:30', status: 'REALIZADA', administeredAt: '2025-02-18T08:30:00Z', administeredBy: 'Lic. Gonzalo Rossi' },
      { id: 'med-3', hospitalizationId: 'hosp-1', patientId: 'pat-1', drugName: 'Tramadol SC', dose: '65 mg (1.3 ml SC)', route: 'SC', frequencyHours: 8, scheduledTime: '14:00', status: 'PROGRAMADA' },
    ],
    tasks: [
      { id: 'tsk-1', time: '08:00', title: 'Control de Signos Vitales y Glucemia', type: 'SIGNOS', isCompleted: true, completedAt: '2025-02-18T08:15:00Z', completedBy: 'Lic. Gonzalo Rossi' },
      { id: 'tsk-2', time: '10:00', title: 'Evaluar tolerancia a agua fresca', type: 'ALIMENTACION', isCompleted: true, completedAt: '2025-02-18T10:05:00Z', completedBy: 'Lic. Gonzalo Rossi' },
      { id: 'tsk-3', time: '13:00', title: 'Paseo higiénico de 5 minutos', type: 'SIGNOS', isCompleted: false },
      { id: 'tsk-4', time: '14:00', title: 'Administración de Tramadol SC', type: 'MEDICACION', isCompleted: false },
    ],
    hourlySheet: [
      { id: 'hs-1', timestamp: '20:00', temperature: 39.4, heartRate: 132, respiratoryRate: 34, bloodPressure: '105/65 (78)', fluidStatus: '80 ml/h Ringer Lactato', observations: 'Ingreso a internación, colocación de catéter 20G.', staffName: 'Lic. Gonzalo Rossi' },
      { id: 'hs-2', timestamp: '00:00', temperature: 39.2, heartRate: 124, respiratoryRate: 30, bloodPressure: '110/70 (83)', fluidStatus: '80 ml/h', observations: 'Descansando en posición esternal, sin vómitos.', staffName: 'Lic. Gonzalo Rossi' },
      { id: 'hs-3', timestamp: '04:00', temperature: 38.9, heartRate: 115, respiratoryRate: 26, bloodPressure: '112/72 (85)', fluidStatus: '80 ml/h', observations: 'Paciente tranquilo, micción espontánea.', staffName: 'Lic. Gonzalo Rossi' },
      { id: 'hs-4', timestamp: '08:00', temperature: 39.1, heartRate: 118, respiratoryRate: 28, bloodPressure: '115/72 (86)', fluidStatus: '80 ml/h', observations: 'Alerta, buen ánimo.', staffName: 'Dr. Martín López' },
    ],
    intervalHours: 4,
    nextVitalsTime: '12:00',
    status: 'ACTIVA',
    branchId: 'branch-1',
  },
  {
    id: 'hosp-2',
    patientId: 'pat-4',
    vetInChargeId: 'user-2',
    vetInChargeName: 'Dra. Carolina Silva',
    sector: 'FELINOS',
    kennelNumber: 'FEL-03',
    admittedAt: '2025-02-17T22:00:00Z',
    primaryDiagnosis: 'Obstrucción uretral felina (FLUTD / Estruvitas)',
    priority: 'CRITICO',
    fluidTherapy: {
      isActive: true,
      solutionType: 'Cloruro de Sodio 0.9%',
      volumeTotalMl: 500,
      rateMlPerHour: 15,
      dropsPerMinute: 15,
      infusionRoute: 'IV',
      startedAt: '2025-02-17T23:00:00Z',
      prescribedBy: 'Dra. Carolina Silva',
    },
    feeding: {
      dietType: 'ORAL',
      foodBrand: 'Royal Canin Urinary S/O Húmedo',
      amountGramsOrMl: 50,
      frequency: 'Cada 8 horas',
      tolerance: 'EXCELENTE',
    },
    eliminations: [
      { id: 'el-3', timestamp: '2025-02-18T08:00:00Z', type: 'MICCION', amount: 'MODERADA', aspect: 'Orina clara en bolsa colectora (45 ml en 6h)', registeredBy: 'Lic. Gonzalo Rossi' },
    ],
    medications: [
      { id: 'med-4', hospitalizationId: 'hosp-2', patientId: 'pat-4', drugName: 'Prazosina (Minipres 0.5mg)', dose: '0.5 mg oral', route: 'ORAL', frequencyHours: 12, scheduledTime: '08:00', status: 'REALIZADA', administeredAt: '2025-02-18T08:00:00Z', administeredBy: 'Lic. Gonzalo Rossi' },
      { id: 'med-5', hospitalizationId: 'hosp-2', patientId: 'pat-4', drugName: 'Buprenorfina SL', dose: '0.015 mg/kg (0.08 ml)', route: 'ORAL', frequencyHours: 8, scheduledTime: '14:00', status: 'PROGRAMADA' },
    ],
    tasks: [
      { id: 'tsk-5', time: '08:00', title: 'Medición de volumen en bolsa colectora', type: 'SIGNOS', isCompleted: true, completedAt: '2025-02-18T08:10:00Z', completedBy: 'Lic. Gonzalo Rossi' },
      { id: 'tsk-6', time: '12:00', title: 'Control de dolor pélvico y fijación de sonda', type: 'SIGNOS', isCompleted: false },
    ],
    hourlySheet: [
      { id: 'hs-5', timestamp: '23:00', temperature: 37.9, heartRate: 190, respiratoryRate: 32, bloodPressure: '135/85 (101)', observations: 'Sondaje uretral exitoso bajo sedación. Lavaje vesical.', staffName: 'Dra. Carolina Silva' },
      { id: 'hs-6', timestamp: '04:00', temperature: 38.2, heartRate: 180, respiratoryRate: 28, bloodPressure: '130/80 (96)', observations: 'Orina clara en bolsa colectora.', staffName: 'Lic. Gonzalo Rossi' },
      { id: 'hs-7', timestamp: '08:00', temperature: 38.3, heartRate: 175, respiratoryRate: 28, bloodPressure: '125/78 (93)', observations: 'Apetito conservado, tolera alimento húmedo.', staffName: 'Lic. Gonzalo Rossi' },
    ],
    intervalHours: 4,
    nextVitalsTime: '12:00',
    status: 'ACTIVA',
    branchId: 'branch-1',
  },
];

export const INITIAL_SURGERIES: SurgeryRecord[] = [
  {
    id: 'surg-1',
    patientId: 'pat-5',
    procedureName: 'Osteosíntesis TPLO (Tibial Plateau Leveling Osteotomy)',
    surgeonName: 'Dr. Martín López',
    anesthetistName: 'Dra. Carolina Silva',
    branchId: 'branch-1',
    date: '2025-02-02',
    startTime: '09:00',
    endTime: '11:30',
    preOpAssessment: {
      asaGrade: 'II',
      fastingHours: 8,
      labReviewed: true,
      risksAlerts: 'Sin contraindicaciones. Ángulo de platillo tibial inicial: 28°.',
    },
    anesthesiaProtocol: {
      premedication: 'Dexmedetomidina 5 mcg/kg + Metadona 0.3 mg/kg IM',
      induction: 'Propofol 4 mg/kg IV',
      maintenance: 'Isoflurano 1.5% en O2 100%',
      analgesia: 'Bloqueo perineural femoral y ciático con Bupivacaína 0.5%',
      monitoringPoints: [
        { time: '09:15', heartRate: 85, respiratoryRate: 14, systolicBP: 110, diastolicBP: 65, spo2: 99, etco2: 38, temperature: 37.8, isoOrSevoPercent: 1.5, oxygenFlowLMin: 1.0, fluidsGivenMl: 100 },
        { time: '09:45', heartRate: 80, respiratoryRate: 12, systolicBP: 115, diastolicBP: 70, spo2: 99, etco2: 39, temperature: 37.5, isoOrSevoPercent: 1.5, oxygenFlowLMin: 1.0, fluidsGivenMl: 250 },
        { time: '10:30', heartRate: 88, respiratoryRate: 14, systolicBP: 120, diastolicBP: 75, spo2: 99, etco2: 37, temperature: 37.2, isoOrSevoPercent: 1.2, oxygenFlowLMin: 1.0, fluidsGivenMl: 450 },
      ],
      milestones: {
        inductionTime: '09:00',
        intubationTime: '09:05',
        incisionTime: '09:20',
        sutureTime: '11:15',
        extubationTime: '11:25',
        recoveryTime: '11:45',
      },
    },
    surgicalTechnique: 'Abordaje medial a la tibia proximal izquierda. Osteotomía radial TPLO. Rotación para corregir ángulo a 5°. Fijación con placa de titanio bloqueada TPLO 3.5mm.',
    findings: 'Ruptura completa del ligamento cruzado craneal con menisco medial íntegro.',
    materialsUsed: [
      { productId: 'prod-4', name: 'Ringer Lactato Baxter 500ml', quantity: 1 },
    ],
    postOpOrders: 'Cefalexina 25 mg/kg c/12h x 10 días. Meloxicam 0.1 mg/kg c/24h x 5 días. Reposo estricto.',
    status: 'FINALIZADA',
  },
  {
    id: 'surg-2',
    patientId: 'pat-3',
    procedureName: 'Rinoplastia de Narinas & Resección de Paladar Blando (BOAS)',
    surgeonName: 'Dr. Martín López',
    anesthetistName: 'Dra. Carolina Silva',
    branchId: 'branch-1',
    date: '2026-08-25',
    startTime: '10:00',
    preOpAssessment: {
      asaGrade: 'III',
      fastingHours: 8,
      labReviewed: true,
      risksAlerts: 'Braquicefálico con riesgo de vía aérea. Preoxigenar.',
    },
    anesthesiaProtocol: {
      premedication: 'Butorfanol 0.2 mg/kg + Midazolam 0.2 mg/kg IV',
      induction: 'Propofol 5 mg/kg IV rápido con intubación inmediata',
      maintenance: 'Isoflurano 1.5%',
      analgesia: 'Dexametasona 0.1 mg/kg antiinflamatorio laríngeo',
      monitoringPoints: [],
      milestones: {
        inductionTime: '10:00',
        intubationTime: '10:05',
        incisionTime: '10:15',
        sutureTime: '11:15',
        extubationTime: '11:30',
        recoveryTime: '11:45',
      },
    },
    surgicalTechnique: 'Alaplastia en cuña vertical bilateral de narinas + Estafiloplastia con bisturí de alta frecuencia.',
    findings: 'Estenosis narinas Grado III y elongación caudal del velo del paladar 8mm.',
    materialsUsed: [],
    postOpOrders: 'Dexametasona 0.1 mg/kg DU. Hielo local. Dieta blanda.',
    status: 'PROGRAMADA',
  },
];

export const INITIAL_LABS: LaboratoryOrder[] = [
  {
    id: 'lab-1',
    orderNumber: 'LAB-2025-0089',
    patientId: 'pat-1',
    testType: 'HEMOGRAMA_COMPLETO',
    requestedBy: 'Dr. Martín López',
    requestedAt: '2025-02-17T20:30:00Z',
    sampleCollectedAt: '2025-02-17T20:45:00Z',
    resultsReadyAt: '2025-02-17T21:40:00Z',
    status: 'FINALIZADO',
    results: [
      { parameter: 'Hematocrito', value: 48, unit: '%', referenceRange: '37 - 55', isAbnormal: false },
      { parameter: 'Glóbulos Blancos', value: 16800, unit: '/uL', referenceRange: '6000 - 17000', isAbnormal: false },
      { parameter: 'Neutrófilos Segmentados', value: 84, unit: '%', referenceRange: '60 - 77', isAbnormal: true },
      { parameter: 'Plaquetas', value: 290000, unit: '/uL', referenceRange: '200000 - 500000', isAbnormal: false },
      { parameter: 'Urea', value: 42, unit: 'mg/dL', referenceRange: '20 - 50', isAbnormal: false },
      { parameter: 'Creatinina', value: 1.1, unit: 'mg/dL', referenceRange: '0.6 - 1.4', isAbnormal: false },
      { parameter: 'Glucemia', value: 104, unit: 'mg/dL', referenceRange: '70 - 110', isAbnormal: false },
    ],
    diagnosticReport: 'Neutrofilia leve por estrés agudo. Perfil renal y glucosa normales.',
    conclusions: 'Sin alteraciones de gravedad. Respuesta a proceso inflamatorio agudo.',
  },
  {
    id: 'lab-2',
    orderNumber: 'LAB-2025-0075',
    patientId: 'pat-2',
    testType: 'PERFIL_BIOQUIMICO_RENAL_HEPATICO',
    requestedBy: 'Dra. Carolina Silva',
    requestedAt: '2025-02-15T11:00:00Z',
    sampleCollectedAt: '2025-02-15T11:15:00Z',
    resultsReadyAt: '2025-02-15T12:30:00Z',
    status: 'FINALIZADO',
    results: [
      { parameter: 'Creatinina', value: 2.1, unit: 'mg/dL', referenceRange: '0.8 - 1.8', isAbnormal: true },
      { parameter: 'Urea', value: 68, unit: 'mg/dL', referenceRange: '30 - 65', isAbnormal: true },
      { parameter: 'SDMA', value: 16, unit: 'ug/dL', referenceRange: '0 - 14', isAbnormal: true },
      { parameter: 'Fósforo', value: 4.8, unit: 'mg/dL', referenceRange: '3.0 - 6.0', isAbnormal: false },
      { parameter: 'Potasio', value: 4.1, unit: 'mEq/L', referenceRange: '3.5 - 5.5', isAbnormal: false },
    ],
    diagnosticReport: 'Azotemia renal leve estable concordante con ERC IRIS Estadio 2.',
    conclusions: 'Enfermedad renal compensada con buen control electrolítico.',
  },
];

export const INITIAL_LAB_ORDERS: LaboratoryOrder[] = INITIAL_LABS;

export const INITIAL_IMAGING: ImagingStudy[] = [
  {
    id: 'img-1',
    studyNumber: 'RX-2025-0142',
    patientId: 'pat-1',
    modality: 'RADIOGRAFIA',
    region: 'Abdomen Simple (Proyecciones LL y VD)',
    requestedBy: 'Dr. Martín López',
    performedBy: 'Dra. Florencia Bianchi',
    date: '2025-02-17',
    report: 'Estómago con moderada cantidad de gas sin efecto masa ni signo de torsión (descartado GDV). Asas delgadas fisiológicas.',
    conclusion: 'Gastritis aguda y aerofagia leve. Sin obstrucción radiodensa.',
    images: [{ id: 'im-1', url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800', caption: 'RX Abdomen LL' }],
    status: 'INFORMADO',
  },
  {
    id: 'img-2',
    studyNumber: 'RX-2025-0130',
    patientId: 'pat-6',
    modality: 'RADIOGRAFIA',
    region: 'Tórax Lateral y VD',
    requestedBy: 'Dra. Carolina Silva',
    performedBy: 'Dra. Florencia Bianchi',
    date: '2025-02-12',
    report: 'Silueta cardíaca aumentada. Índice de Buchanan (VHS) = 11.2 vértebras (Ref < 10.5). Sin edema pulmonar.',
    conclusion: 'Cardiomegalia izquierda compatible con ACVIM Estadio C compensado.',
    images: [{ id: 'im-2', url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800', caption: 'RX Tórax LL' }],
    status: 'INFORMADO',
  },
];

export const INITIAL_VACCINES: VaccinationRecord[] = [
  {
    id: 'vac-1',
    patientId: 'pat-1',
    vaccineName: 'Vacuna Séxtuple Canina (DHPPi/L)',
    manufacturer: 'MSD Animal Health',
    batchNumber: 'NOB-2024-88A',
    expirationDate: '2025-12-31',
    administeredDate: '2024-04-15',
    administeredBy: 'Dr. Martín López',
    vetLicense: 'MP 8412',
    nextDueDate: '2025-04-15',
    certificateGenerated: true,
  },
  {
    id: 'vac-2',
    patientId: 'pat-1',
    vaccineName: 'Vacuna Antirrábica',
    manufacturer: 'Zoetis',
    batchNumber: 'RAB-2024-119',
    expirationDate: '2026-03-30',
    administeredDate: '2024-04-15',
    administeredBy: 'Dr. Martín López',
    vetLicense: 'MP 8412',
    nextDueDate: '2025-04-15',
    certificateGenerated: true,
  },
  {
    id: 'vac-3',
    patientId: 'pat-2',
    vaccineName: 'Vacuna Triple Felina (FVRCP)',
    manufacturer: 'MSD Animal Health',
    batchNumber: 'FEL-2024-402',
    expirationDate: '2025-10-31',
    administeredDate: '2024-08-10',
    administeredBy: 'Dra. Carolina Silva',
    vetLicense: 'MP 9520',
    nextDueDate: '2025-08-10',
    certificateGenerated: true,
  },
  {
    id: 'vac-4',
    patientId: 'pat-3',
    vaccineName: 'Vacuna Séxtuple Canina',
    manufacturer: 'Zoetis',
    batchNumber: 'ZOE-2024-554',
    expirationDate: '2025-09-30',
    administeredDate: '2024-03-20',
    administeredBy: 'Dr. Martín López',
    vetLicense: 'MP 8412',
    nextDueDate: '2025-03-20',
    certificateGenerated: true,
  },
];

export const INITIAL_VACCINATIONS: VaccinationRecord[] = INITIAL_VACCINES;

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    code: 'FAR-001',
    commercialName: 'Cerenia Inyectable (Maropitant 10mg/ml)',
    activeIngredient: 'Maropitant Citrato',
    category: 'MEDICAMENTO',
    concentration: '10 mg/ml',
    presentation: 'Frasco ampolla x 20 ml',
    laboratory: 'Zoetis',
    costPrice: 42000,
    salePrice: 65000,
    currentStock: 14,
    minStock: 5,
    currentBatch: 'LT-240901',
    expirationDate: '2026-09-01',
    supplier: 'Distribuidora Veterinaria Central',
    branchId: 'branch-1',
  },
  {
    id: 'prod-2',
    code: 'FAR-002',
    commercialName: 'Clavamox / Synulox 500mg',
    activeIngredient: 'Amoxicilina + Ácido Clavulánico',
    category: 'MEDICAMENTO',
    concentration: '500 mg',
    presentation: 'Caja x 20 comprimidos',
    laboratory: 'Zoetis',
    costPrice: 18500,
    salePrice: 28000,
    currentStock: 28,
    minStock: 10,
    currentBatch: 'LT-241105',
    expirationDate: '2026-11-05',
    supplier: 'Distribuidora Veterinaria Central',
    branchId: 'branch-1',
  },
  {
    id: 'prod-3',
    code: 'FAR-003',
    commercialName: 'Vetmedin 5mg (Pimobendan)',
    activeIngredient: 'Pimobendan',
    category: 'MEDICAMENTO',
    concentration: '5 mg',
    presentation: 'Frasco x 50 comprimidos',
    laboratory: 'Boehringer Ingelheim',
    costPrice: 58000,
    salePrice: 89000,
    currentStock: 8,
    minStock: 4,
    currentBatch: 'LT-240812',
    expirationDate: '2026-08-12',
    supplier: 'FarmaVet Argentina',
    branchId: 'branch-1',
  },
  {
    id: 'prod-4',
    code: 'INS-010',
    commercialName: 'Solución Ringer Lactato 500ml',
    activeIngredient: 'Electrolitos balanceados',
    category: 'DESCARTABLE',
    concentration: '500 ml',
    presentation: 'Sachet con pico',
    laboratory: 'Baxter',
    costPrice: 2800,
    salePrice: 5500,
    currentStock: 45,
    minStock: 20,
    currentBatch: 'LT-250102',
    expirationDate: '2027-01-02',
    supplier: 'Insumos Médicos Sur',
    branchId: 'branch-1',
  },
  {
    id: 'prod-5',
    code: 'PAR-005',
    commercialName: 'Bravecto Perros 20-40 kg',
    activeIngredient: 'Fluralaner 1000mg',
    category: 'MEDICAMENTO',
    concentration: '1000 mg',
    presentation: 'Comprimido masticable',
    laboratory: 'MSD Animal Health',
    costPrice: 32000,
    salePrice: 48000,
    currentStock: 12,
    minStock: 5,
    currentBatch: 'LT-241010',
    expirationDate: '2026-10-10',
    supplier: 'MSD Argentina',
    branchId: 'branch-1',
  },
  {
    id: 'prod-6',
    code: 'PAR-006',
    commercialName: 'NexGard Spectra 7.5-15 kg',
    activeIngredient: 'Afoxolaner + Milbemicina',
    category: 'MEDICAMENTO',
    concentration: 'Mediano',
    presentation: 'Caja x 3 comprimidos',
    laboratory: 'Boehringer Ingelheim',
    costPrice: 38000,
    salePrice: 56000,
    currentStock: 16,
    minStock: 6,
    currentBatch: 'LT-241201',
    expirationDate: '2026-12-01',
    supplier: 'FarmaVet Argentina',
    branchId: 'branch-1',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'app-1',
    patientId: 'pat-3',
    ownerId: 'owner-3',
    vetId: 'user-1',
    branchId: 'branch-1',
    date: '2025-02-18',
    time: '10:30',
    durationMinutes: 30,
    type: 'CIRUGIA',
    reason: 'Evaluación prequirúrgica final para cirugía BOAS',
    status: 'CONFIRMADO',
  },
  {
    id: 'app-2',
    patientId: 'pat-6',
    ownerId: 'owner-6',
    vetId: 'user-2',
    branchId: 'branch-1',
    date: '2025-02-18',
    time: '11:30',
    durationMinutes: 30,
    type: 'CONTROL',
    reason: 'Control cardiológico trimestral y ajuste de medicación',
    status: 'CONFIRMADO',
  },
  {
    id: 'app-3',
    patientId: 'pat-7',
    ownerId: 'owner-6',
    vetId: 'user-2',
    branchId: 'branch-1',
    date: '2025-02-18',
    time: '15:00',
    durationMinutes: 30,
    type: 'CONSULTA_GENERAL',
    reason: 'Revisión de motilidad en conejo Mini Lop',
    status: 'CONFIRMADO',
  },
];

export const INITIAL_TRIAGE: TriageEntry[] = [
  {
    id: 'tri-1',
    patientId: 'pat-1',
    ownerId: 'owner-1',
    arrivedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    waitTimeMinutes: 20,
    priority: 'CRITICO',
    chiefComplaint: 'Vómitos severos incoercibles y dolor abdominal agudo',
    assignedVetId: 'user-1',
    initialTemp: 39.4,
    initialHeartRate: 132,
    initialMucous: 'CONGESTIVAS',
    status: 'DERIVADO_INTERNACION',
  },
];

export const INITIAL_PROBLEMS: PatientProblem[] = [
  {
    id: 'prob-1',
    patientId: 'pat-1',
    title: 'Gastroenteritis Aguda Severa',
    description: 'Vómitos biliosos frecuentes y dolor epigástrico.',
    status: 'ACTIVO',
    onsetDate: '2025-02-17',
    vetName: 'Dr. Martín López',
  },
  {
    id: 'prob-2',
    patientId: 'pat-2',
    title: 'Enfermedad Renal Crónica IRIS Estadio 2',
    description: 'Creatinina 2.1 mg/dL, SDMA 16 ug/dL. En tratamiento dietario y con Amlodipino.',
    status: 'ACTIVO',
    onsetDate: '2024-08-10',
    vetName: 'Dra. Carolina Silva',
  },
  {
    id: 'prob-3',
    patientId: 'pat-3',
    title: 'Síndrome Obstructivo Braquicefálico (BOAS)',
    description: 'Estenosis severa de narinas + elongación de paladar blando.',
    status: 'ACTIVO',
    onsetDate: '2024-11-05',
    vetName: 'Dr. Martín López',
  },
  {
    id: 'prob-4',
    patientId: 'pat-4',
    title: 'Obstrucción Uretral por Estruvitas (FLUTD)',
    description: 'Sonda vesical colocada con éxito.',
    status: 'ACTIVO',
    onsetDate: '2025-02-17',
    vetName: 'Dra. Carolina Silva',
  },
  {
    id: 'prob-5',
    patientId: 'pat-5',
    title: 'Ruptura de Ligamento Cruzado Craneal Izquierdo',
    description: 'Corregido mediante osteotomía TPLO.',
    status: 'RESUELTO',
    onsetDate: '2025-01-20',
    resolvedDate: '2025-02-14',
    vetName: 'Dr. Martín López',
  },
  {
    id: 'prob-6',
    patientId: 'pat-6',
    title: 'Insuficiencia Valvular Mitral ACVIM Estadio C',
    description: 'Soplo apical IV/VI, en tratamiento con Pimobendan y Furosemida.',
    status: 'ACTIVO',
    onsetDate: '2024-03-12',
    vetName: 'Dra. Carolina Silva',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: '0001-00045201',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-18T09:30:00Z',
    ownerId: 'owner-1',
    patientId: 'pat-1',
    customerName: 'Juan Pablo Pérez Rossi',
    customerDniCuit: '32.458.912',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-1', description: 'Atención de Urgencia en Guardia 24hs', quantity: 1, unitPrice: 25000, subtotal: 25000 },
      { id: 'item-2', description: 'Día de Internación en Unidad de Cuidados Intensivos (UCI)', quantity: 1, unitPrice: 45000, subtotal: 45000 },
      { id: 'item-3', description: 'Hemograma Completo + Bioquímica de Urgencia', quantity: 1, unitPrice: 28000, subtotal: 28000 },
      { id: 'item-4', description: 'Radiografía Digital de Abdomen (2 proyecciones)', quantity: 1, unitPrice: 22000, subtotal: 22000 },
      { id: 'item-5', description: 'Insumos de Fluidoterapia + Sachet Ringer Lactato', quantity: 1, unitPrice: 9500, subtotal: 9500 },
    ],
    totalAmount: 129500,
    paymentMethod: 'TRANSFERENCIA',
    caeNumber: '75128904512390',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
  {
    id: 'inv-2',
    invoiceNumber: '0001-00008912',
    type: 'FACTURA_A',
    pointOfSale: 1,
    date: '2025-02-10T17:00:00Z',
    ownerId: 'owner-3',
    patientId: 'pat-3',
    customerName: 'Esteban Ríos',
    customerDniCuit: '20-35120489-3',
    customerTaxCondition: 'IVA Responsable Inscripto',
    items: [
      { id: 'item-6', description: 'Consulta Médica de Especialidad Quirúrgica', quantity: 1, unitPrice: 22000, subtotal: 22000 },
      { id: 'item-7', description: 'Estudio Prequirúrgico Cardiológico + ECG', quantity: 1, unitPrice: 30000, subtotal: 30000 },
    ],
    totalAmount: 52000,
    paymentMethod: 'MERCADOPAGO_QR',
    caeNumber: '75128904512391',
    caeExpirationDate: '2025-02-20',
    branchId: 'branch-1',
  },
  {
    id: 'inv-3',
    invoiceNumber: '0001-00008913',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-14T11:00:00Z',
    ownerId: 'owner-2',
    patientId: 'pat-2',
    customerName: 'María Eugenia González',
    customerDniCuit: '28.914.502',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-8', description: 'Consulta Médica de Control Nefrológico', quantity: 1, unitPrice: 20500, subtotal: 20500 },
      { id: 'item-9', description: 'Panel Renal Felino + SDMA IDEXX', quantity: 1, unitPrice: 35000, subtotal: 35000 },
      { id: 'item-10', description: 'Medicamentos Crónicos (Amlodipino + Benazepril)', quantity: 2, unitPrice: 32500, subtotal: 65000 },
    ],
    totalAmount: 120500,
    paymentMethod: 'TARJETA_DEBITO',
    caeNumber: '75128904512392',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
  {
    id: 'inv-4',
    invoiceNumber: '0001-00008914',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-15T16:00:00Z',
    ownerId: 'owner-5',
    patientId: 'pat-5',
    customerName: 'Alejandro Morales',
    customerDniCuit: '20-25680993-8',
    customerTaxCondition: 'IVA Responsable Inscripto',
    items: [
      { id: 'item-11', description: 'Consulta Guardia Traumatológica', quantity: 1, unitPrice: 25000, subtotal: 25000 },
      { id: 'item-12', description: 'Tratamiento y Curaciones Especiales', quantity: 1, unitPrice: 175000, subtotal: 175000 },
    ],
    totalAmount: 200000,
    paymentMethod: 'TRANSFERENCIA',
    caeNumber: '75128904512393',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
  {
    id: 'inv-5',
    invoiceNumber: '0001-00008915',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-02T14:00:00Z',
    ownerId: 'owner-5',
    patientId: 'pat-5',
    customerName: 'Alejandro Morales',
    customerDniCuit: '20-25680993-8',
    customerTaxCondition: 'IVA Responsable Inscripto',
    items: [
      { id: 'item-13', description: 'Cirugía Compleja Osteosíntesis TPLO', quantity: 1, unitPrice: 238000, subtotal: 238000 },
      { id: 'item-14', description: 'Anestesia Inhalatoria Especializada con Bloqueos', quantity: 1, unitPrice: 90000, subtotal: 90000 },
    ],
    totalAmount: 328000,
    paymentMethod: 'TARJETA_CREDITO',
    caeNumber: '75128904512394',
    caeExpirationDate: '2025-02-15',
    branchId: 'branch-1',
  },
  {
    id: 'inv-6',
    invoiceNumber: '0001-00008916',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-17T22:30:00Z',
    ownerId: 'owner-4',
    patientId: 'pat-4',
    customerName: 'Lucía Fernández',
    customerDniCuit: '39.840.112',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-15', description: 'Manejo de Emergencia Obstrucción FLUTD + Desobstrucción', quantity: 1, unitPrice: 85000, subtotal: 85000 },
      { id: 'item-16', description: '2 Días de Internación Felina con Monitoreo de Diuresis', quantity: 2, unitPrice: 87500, subtotal: 175000 },
    ],
    totalAmount: 260000,
    paymentMethod: 'MERCADOPAGO_QR',
    caeNumber: '75128904512395',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
  {
    id: 'inv-7',
    invoiceNumber: '0001-00008917',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-12T12:00:00Z',
    ownerId: 'owner-6',
    patientId: 'pat-6',
    customerName: 'Florencia Vázquez',
    customerDniCuit: '41.205.881',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-17', description: 'Fármacos Cardiológicos (Vetmedin 5mg x 50 comp)', quantity: 1, unitPrice: 89000, subtotal: 89000 },
      { id: 'item-18', description: 'Antiparasitario NexGard Spectra', quantity: 1, unitPrice: 21000, subtotal: 21000 },
    ],
    totalAmount: 110000,
    paymentMethod: 'EFECTIVO',
    caeNumber: '75128904512396',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
  {
    id: 'inv-8',
    invoiceNumber: '0001-00008918',
    type: 'FACTURA_B',
    pointOfSale: 1,
    date: '2025-02-16T18:00:00Z',
    ownerId: 'owner-1',
    patientId: 'pat-1',
    customerName: 'Juan Pablo Pérez Rossi',
    customerDniCuit: '32.458.912',
    customerTaxCondition: 'Consumidor Final',
    items: [
      { id: 'item-19', description: 'Insumos Farmacia Hospitalaria y Descartables', quantity: 1, unitPrice: 80000, subtotal: 80000 },
    ],
    totalAmount: 80000,
    paymentMethod: 'TRANSFERENCIA',
    caeNumber: '75128904512397',
    caeExpirationDate: '2025-02-28',
    branchId: 'branch-1',
  },
];

export const INITIAL_ESTIMATES: Estimate[] = [
  {
    id: 'est-1',
    estimateNumber: 'PRES-2025-0012',
    ownerId: 'owner-3',
    patientId: 'pat-3',
    date: '2025-02-10',
    validUntil: '2025-03-10',
    items: [
      { id: 'it-e1', description: 'Cirugía Rinoplastia de Narinas + Paladar Blando (BOAS)', quantity: 1, unitPrice: 185000, subtotal: 185000 },
      { id: 'it-e2', description: 'Anestesia General Inhalatoria + Monitoreo Multiparamétrico', quantity: 1, unitPrice: 65000, subtotal: 65000 },
      { id: 'it-e3', description: 'Día de Recuperación Posquirúrgica en Sala', quantity: 1, unitPrice: 35000, subtotal: 35000 },
    ],
    totalAmount: 285000,
    notes: 'Presupuesto válido por 30 días. Incluye controles posquirúrgicos inmediatos.',
    status: 'ACEPTADO',
  },
];

export const INITIAL_DOCUMENTS: ClinicalDocument[] = [
  {
    id: 'doc-1',
    type: 'CONSENTIMIENTO_CIRUGIA_ANESTESIA',
    title: 'Consentimiento Informado para Procedimiento Quirúrgico & Anestesia General',
    patientId: 'pat-5',
    ownerId: 'owner-5',
    vetName: 'Dr. Martín López',
    createdAt: '2025-02-02T08:30:00Z',
    content: 'Por medio de la presente, el tutor Alejandro Morales autoriza la realización de la cirugía de Osteosíntesis TPLO en Nina.',
    signedByOwnerName: 'Alejandro Morales',
    signedByOwnerDni: '25.680.993',
    signatureDataUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    isSigned: true,
  },
];

export const INITIAL_CASH_SESSIONS: CashRegisterSession[] = [
  {
    id: 'cash-1',
    branchId: 'branch-1',
    openedAt: '2025-02-18T07:00:00Z',
    openedBy: 'Matías Beltrán',
    initialCash: 50000,
    totalIncomeCash: 85000,
    totalIncomeDigital: 465000,
    totalExpenses: 12000,
    isClosed: false,
  },
];

export const INITIAL_CASH_SESSION: CashRegisterSession = INITIAL_CASH_SESSIONS[0];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2025-02-17T20:30:00Z',
    userName: 'Dr. Martín López',
    userRole: 'VETERINARIO',
    action: 'INGRESO_INTERNACION_UCI',
    entity: 'Hospitalization',
    entityId: 'hosp-1',
    details: 'Paciente Toby ingresado en UCI Canil #1 con Ringer Lactato a 80 ml/h.',
  },
];
